insert into customer (id, name, funds, type) values (1, 'Rachael Chaikovski', 950, 'Daqiao');
insert into customer (id, name, funds, type) values (2, 'Fabien Elphinstone', 825, 'Karanlukh');
insert into customer (id, name, funds, type) values (3, 'Bern Bennison', 86, 'Casilda');
insert into customer (id, name, funds, type) values (4, 'Kali Sear', 75, 'Tiancheng');
insert into customer (id, name, funds, type) values (5, 'Alix Minshaw', 349, 'Yanghong');
insert into customer (id, name, funds, type) values (6, 'Matthieu Vannet', 505, 'Cajueiro');
insert into customer (id, name, funds, type) values (7, 'Ethyl Hummerston', 324, 'Bełk');
insert into customer (id, name, funds, type) values (8, 'Kippie Coppenhall', 714, 'Santa Ana');
insert into customer (id, name, funds, type) values (9, 'Kristoffer Ruttgers', 389, 'Edinburgh of the Seven Seas');
insert into customer (id, name, funds, type) values (10, 'Annissa Ciobotaru', 789, 'Kidatu');
insert into customer (id, name, funds, type) values (11, 'Dominica Cantillon', 79, 'Ketangi');
insert into customer (id, name, funds, type) values (12, 'Pavel Mouse', 178, 'Pilar');
insert into customer (id, name, funds, type) values (13, 'Willy Bredgeland', 354, 'Bantarjati');
insert into customer (id, name, funds, type) values (14, 'Sergeant Zavattiero', 923, 'Chengyang');
insert into customer (id, name, funds, type) values (15, 'Bil Tuckwood', 838, 'Tangdukou');
insert into customer (id, name, funds, type) values (16, 'Prescott Naish', 873, 'Zhongling');
insert into customer (id, name, funds, type) values (17, 'Algernon Kiely', 99, 'Rennes');
insert into customer (id, name, funds, type) values (18, 'Charlot MacNally', 942, 'Taiping');
insert into customer (id, name, funds, type) values (19, 'Larine Pegrum', 557, 'Ćićevac');
insert into customer (id, name, funds, type) values (20, 'Binny Dunkersley', 699, 'Knurów');
insert into customer (id, name, funds, type) values (21, 'Zita Roussel', 51, 'Bonneuil-sur-Marne');
insert into customer (id, name, funds, type) values (22, 'Gladi Attride', 77, 'Sunne');
insert into customer (id, name, funds, type) values (23, 'Udell Debnam', 900, 'Buan');
insert into customer (id, name, funds, type) values (24, 'Georgiana Askaw', 26, 'Xigangzi');
insert into customer (id, name, funds, type) values (25, 'Michal Sonnenschein', 437, 'Obubra');
insert into customer (id, name, funds, type) values (26, 'Yetta Paraman', 262, 'Drammen');
insert into customer (id, name, funds, type) values (27, 'Amy Coath', 921, 'Malinta');
insert into customer (id, name, funds, type) values (28, 'Hildagard Hullin', 764, 'Changhan');
insert into customer (id, name, funds, type) values (29, 'Rozalie Laughton', 593, 'Cadiz');
insert into customer (id, name, funds, type) values (30, 'Iolande Troop', 351, 'Quintão');
insert into customer (id, name, funds, type) values (31, 'Ramsey Kynaston', 344, 'Anápolis');
insert into customer (id, name, funds, type) values (32, 'Georgeanna Danilowicz', 322, 'Chavdar');
insert into customer (id, name, funds, type) values (33, 'Tanya Hakonsen', 534, 'Bhamdoûn el Mhatta');
insert into customer (id, name, funds, type) values (34, 'Hillary Oakenfall', 334, 'Quzi');
insert into customer (id, name, funds, type) values (35, 'Rudie O'' Hogan', 37, 'Al Masallamiyya');
insert into customer (id, name, funds, type) values (36, 'Maryl Desport', 833, 'Guarapari');
insert into customer (id, name, funds, type) values (37, 'Jule Darnody', 738, 'Avellaneda');
insert into customer (id, name, funds, type) values (38, 'Waverly Beecroft', 165, 'Huanghuatan');
insert into customer (id, name, funds, type) values (39, 'Amerigo Velti', 207, 'Sypniewo');
insert into customer (id, name, funds, type) values (40, 'Annadiana Oxe', 549, 'Yajiwa');
insert into customer (id, name, funds, type) values (41, 'Kalil Durgan', 453, 'Guozhuang');
insert into customer (id, name, funds, type) values (42, 'Alla Tender', 488, 'Abuko');
insert into customer (id, name, funds, type) values (43, 'Natty Siemens', 643, 'Verkhn’odniprovs’k');
insert into customer (id, name, funds, type) values (44, 'Genia Sapseed', 726, 'Huyunxiang');
insert into customer (id, name, funds, type) values (45, 'Modesty Pedycan', 917, 'Tiandu');
insert into customer (id, name, funds, type) values (46, 'Sky Sangwine', 673, 'Palaiochóri');
insert into customer (id, name, funds, type) values (47, 'Salvador Yearby', 683, 'Tanggungrejo');
insert into customer (id, name, funds, type) values (48, 'Donna Prowse', 956, 'Xiaolongmen');
insert into customer (id, name, funds, type) values (49, 'Lauraine Meanwell', 301, 'Mūsá Qal‘ah');
insert into customer (id, name, funds, type) values (50, 'Grove Slate', 482, 'Mekarsari');
insert into customer (id, name, funds, type) values (51, 'Alric Opdenort', 239, 'Jovellar');
insert into customer (id, name, funds, type) values (52, 'Onfroi Karadzas', 935, 'Boca Suno');
insert into customer (id, name, funds, type) values (53, 'Conn Sibbert', 343, 'Ararat');
insert into customer (id, name, funds, type) values (54, 'Lorrin Rosewarne', 760, 'Tobilolong');
insert into customer (id, name, funds, type) values (55, 'Elly Bogey', 9, 'Morrison');
insert into customer (id, name, funds, type) values (56, 'Pavla Gritland', 792, 'Killorglin');
insert into customer (id, name, funds, type) values (57, 'Steward Ethelston', 66, 'Gunungmanik');
insert into customer (id, name, funds, type) values (58, 'Ardine Fielder', 647, 'Smokvica');
insert into customer (id, name, funds, type) values (59, 'Darla Tuffin', 468, 'Ibaraki');
insert into customer (id, name, funds, type) values (60, 'Cleve Somes', 720, 'Suwaru');
insert into customer (id, name, funds, type) values (61, 'Tedman Waliszewski', 863, 'Xiatang');
insert into customer (id, name, funds, type) values (62, 'Marcelia Montel', 72, 'Rionegro');
insert into customer (id, name, funds, type) values (63, 'Mavra Levings', 967, 'Tabatinga');
insert into customer (id, name, funds, type) values (64, 'Karmen Eakeley', 776, 'Kedungwringin Satu');
insert into customer (id, name, funds, type) values (65, 'Vernen Vanyatin', 43, 'Zhouxi');
insert into customer (id, name, funds, type) values (66, 'Courtney Veall', 471, 'Kuala Terengganu');
insert into customer (id, name, funds, type) values (67, 'Agretha Apple', 978, 'Belišće');
insert into customer (id, name, funds, type) values (68, 'Dare Dilrew', 31, 'Sanjie');
insert into customer (id, name, funds, type) values (69, 'Estelle Feehily', 141, 'Guadalupe');
insert into customer (id, name, funds, type) values (70, 'Aubry Scrowby', 356, 'Pacanga');
insert into customer (id, name, funds, type) values (71, 'Nolly Whitcombe', 610, 'Bago');
insert into customer (id, name, funds, type) values (72, 'Stanislas Coulthard', 275, 'Bella Vista');
insert into customer (id, name, funds, type) values (73, 'Bernie Billett', 761, 'Myasnikyan');
insert into customer (id, name, funds, type) values (74, 'Bertrand Gormley', 448, 'Gexi');
insert into customer (id, name, funds, type) values (75, 'Hannis Sopper', 380, 'Rudo');
insert into customer (id, name, funds, type) values (76, 'Jazmin Antuoni', 491, 'Haixing');
insert into customer (id, name, funds, type) values (77, 'Cathi Maplethorp', 870, 'Vyatskiye Polyany');
insert into customer (id, name, funds, type) values (78, 'Madalena Shama', 376, 'Dukou');
insert into customer (id, name, funds, type) values (79, 'Phylis Duddell', 856, 'Hāsilpur');
insert into customer (id, name, funds, type) values (80, 'Thea Pardey', 208, 'Las Vegas');
insert into customer (id, name, funds, type) values (81, 'Luz Warbrick', 746, 'Qijiazuo');
insert into customer (id, name, funds, type) values (82, 'Gregg Keeling', 99, 'Utajärvi');
insert into customer (id, name, funds, type) values (83, 'Millard Jinda', 598, 'Montreuil');
insert into customer (id, name, funds, type) values (84, 'Tuckie Hitzschke', 470, 'Rancapeundey');
insert into customer (id, name, funds, type) values (85, 'Mackenzie Lamball', 875, 'Ludbreg');
insert into customer (id, name, funds, type) values (86, 'Lynelle Blazejewski', 102, 'Daxi');
insert into customer (id, name, funds, type) values (87, 'Georgi Persian', 711, 'Kyzylzhar');
insert into customer (id, name, funds, type) values (88, 'Rozanne Reisen', 302, 'Telbang');
insert into customer (id, name, funds, type) values (89, 'Gelya Apdell', 867, 'Houxi');
insert into customer (id, name, funds, type) values (90, 'Barrett Steely', 369, 'Zverevo');
insert into customer (id, name, funds, type) values (91, 'Dillie Gendricke', 548, 'Galūgāh');
insert into customer (id, name, funds, type) values (92, 'Sigfrid Jakubovicz', 274, 'Belyayevka');
insert into customer (id, name, funds, type) values (93, 'Pattie Jarvis', 453, 'Surcubamba');
insert into customer (id, name, funds, type) values (94, 'Whittaker Dykas', 221, 'New Orleans');
insert into customer (id, name, funds, type) values (95, 'Nerte Cohn', 515, 'Villa Atamisqui');
insert into customer (id, name, funds, type) values (96, 'Ulrike Hanfrey', 599, 'Sosnówka');
insert into customer (id, name, funds, type) values (97, 'Hasheem Lambie', 445, 'Majagual');
insert into customer (id, name, funds, type) values (98, 'Ethelin Gashion', 373, 'Banjar Sambangan');
insert into customer (id, name, funds, type) values (99, 'Pandora Martinson', 739, 'Larangan');
insert into customer (id, name, funds, type) values (100, 'Nicolai Bravey', 539, 'Songshan');
insert into customer (id, name, funds, type) values (101, 'Christophorus Betterton', 870, 'Lhokkruet');
insert into customer (id, name, funds, type) values (102, 'Sofia Skeels', 857, 'Spétses');
insert into customer (id, name, funds, type) values (103, 'Reggie Newbury', 555, 'Piraí');
insert into customer (id, name, funds, type) values (104, 'Margeaux Dancey', 596, 'Bełżec');
insert into customer (id, name, funds, type) values (105, 'Cordie Zima', 972, 'Piura');
insert into customer (id, name, funds, type) values (106, 'Benito Daintrey', 387, 'Gyodong');
insert into customer (id, name, funds, type) values (107, 'Grantham Sillett', 637, 'Nabunturan');
insert into customer (id, name, funds, type) values (108, 'Garnet Winter', 931, 'Aurora');
insert into customer (id, name, funds, type) values (109, 'Dolorita Marion', 683, 'Lazaro Cardenas');
insert into customer (id, name, funds, type) values (110, 'Junia Jime', 608, '‘Arīqah');
insert into customer (id, name, funds, type) values (111, 'Sibel Jakoubec', 472, 'Berlin');
insert into customer (id, name, funds, type) values (112, 'Binni Purdey', 231, 'Porangaba');
insert into customer (id, name, funds, type) values (113, 'Alida Kisby', 3, 'Welisara');
insert into customer (id, name, funds, type) values (114, 'Cully Fairtlough', 836, 'Itapecerica da Serra');
insert into customer (id, name, funds, type) values (115, 'Romola Kern', 645, 'Qiaozi');
insert into customer (id, name, funds, type) values (116, 'Rupert Trye', 804, 'Pierreville');
insert into customer (id, name, funds, type) values (117, 'Bartram Pasek', 511, 'Pengilon');
insert into customer (id, name, funds, type) values (118, 'Georgianna Heffernan', 641, 'Dashi');
insert into customer (id, name, funds, type) values (119, 'Alec Fulkes', 304, 'Shanglaxiu');
insert into customer (id, name, funds, type) values (120, 'Emelda Scullion', 722, 'Palencia');
insert into customer (id, name, funds, type) values (121, 'Olivette Cabera', 86, 'La Romana');
insert into customer (id, name, funds, type) values (122, 'Yankee Spooner', 322, 'Göteborg');
insert into customer (id, name, funds, type) values (123, 'Harli Hounson', 715, 'Dasiping');
insert into customer (id, name, funds, type) values (124, 'Tyler Sparrowe', 236, 'Saint Hubert');
insert into customer (id, name, funds, type) values (125, 'Gisella Lapre', 555, 'København');
insert into customer (id, name, funds, type) values (126, 'Yolanda Tees', 300, 'Sancti Spíritus');
insert into customer (id, name, funds, type) values (127, 'Nye Downs', 407, 'Kobylanka');
insert into customer (id, name, funds, type) values (128, 'Letitia Thaxton', 208, 'Tumxuk');
insert into customer (id, name, funds, type) values (129, 'Peirce Chennells', 235, 'Pulosari');
insert into customer (id, name, funds, type) values (130, 'Miriam Kobpal', 508, 'Vohipaho');
insert into customer (id, name, funds, type) values (131, 'Mathias MacColgan', 419, 'Tegalgede Kulon');
insert into customer (id, name, funds, type) values (132, 'Florry Atwel', 213, 'Changyuan');
insert into customer (id, name, funds, type) values (133, 'Brian Sansom', 400, 'Soest');
insert into customer (id, name, funds, type) values (134, 'Nyssa Dono', 489, 'Ciseuseupan');
insert into customer (id, name, funds, type) values (135, 'Zsa zsa Ivanyushkin', 596, 'Túquerres');
insert into customer (id, name, funds, type) values (136, 'Constantia Korba', 156, 'Pittsburgh');
insert into customer (id, name, funds, type) values (137, 'Bird Everwin', 835, 'Saint Louis');
insert into customer (id, name, funds, type) values (138, 'Shaughn Muffin', 783, 'Azogues');
insert into customer (id, name, funds, type) values (139, 'Sherrie Clemencet', 816, 'Moramanga');
insert into customer (id, name, funds, type) values (140, 'Davita Chatel', 581, 'Chinchaypujio');
insert into customer (id, name, funds, type) values (141, 'Jelene Attewill', 335, 'Karangampel');
insert into customer (id, name, funds, type) values (142, 'Ruthann Turford', 129, 'Kosikha');
insert into customer (id, name, funds, type) values (143, 'Bank Kernocke', 814, 'Huangzhuang');
insert into customer (id, name, funds, type) values (144, 'Cecilius Roches', 193, 'Paris 19');
insert into customer (id, name, funds, type) values (145, 'Britta True', 28, 'Przeworsk');
insert into customer (id, name, funds, type) values (146, 'Dietrich Kovacs', 256, 'Koźmin Wielkopolski');
insert into customer (id, name, funds, type) values (147, 'Elyse Tolle', 18, 'Jubaoshan');
insert into customer (id, name, funds, type) values (148, 'Nan Halladey', 520, 'Lorut');
insert into customer (id, name, funds, type) values (149, 'Jarib McGilmartin', 991, 'Santa Cruz');
insert into customer (id, name, funds, type) values (150, 'Anthony Iston', 220, 'Babakan Baru');
insert into customer (id, name, funds, type) values (151, 'Sissie Stobie', 289, 'Uvarovo');
insert into customer (id, name, funds, type) values (152, 'Ronny Lyenyng', 54, 'Şabyā');
insert into customer (id, name, funds, type) values (153, 'Nichols Bedson', 592, 'Gradići');
insert into customer (id, name, funds, type) values (154, 'Clevey Hollebon', 469, 'Lepaterique');
insert into customer (id, name, funds, type) values (155, 'Jamie Adel', 539, 'Yuankeng');
insert into customer (id, name, funds, type) values (156, 'Ethelind Todaro', 74, 'Banjar Sedang');
insert into customer (id, name, funds, type) values (157, 'Nicoli Abbitt', 57, 'Shelabolikha');
insert into customer (id, name, funds, type) values (158, 'Shayne Reding', 60, 'Rancaranji');
insert into customer (id, name, funds, type) values (159, 'Marybelle Saull', 584, 'Huanglong');
insert into customer (id, name, funds, type) values (160, 'Baxy Goodale', 556, 'Tambalisa');
insert into customer (id, name, funds, type) values (161, 'Ruthie Sheehan', 842, 'Lijiaxiang');
insert into customer (id, name, funds, type) values (162, 'Robbie Oldroyde', 369, 'Tagbina');
insert into customer (id, name, funds, type) values (163, 'Vivian Haslam', 779, 'Älvsjö');
insert into customer (id, name, funds, type) values (164, 'Eryn Gude', 439, 'Doblas');
insert into customer (id, name, funds, type) values (165, 'Susie Boffey', 104, 'La Libertad');
insert into customer (id, name, funds, type) values (166, 'Amandi Ghiotto', 999, 'Perugia');
insert into customer (id, name, funds, type) values (167, 'Trudey Phlippi', 218, 'Zhaodong');
insert into customer (id, name, funds, type) values (168, 'Ingrim Bowater', 700, 'Sunchales');
insert into customer (id, name, funds, type) values (169, 'Austen McWilliams', 974, 'Huaishu');
insert into customer (id, name, funds, type) values (170, 'Leonerd Twell', 950, 'Tobi Village');
insert into customer (id, name, funds, type) values (171, 'Ethelind Itzkovwitch', 259, 'Söderköping');
insert into customer (id, name, funds, type) values (172, 'Suzanna Hanshawe', 48, 'Binuangan');
insert into customer (id, name, funds, type) values (173, 'Lisette Rodwell', 445, 'Támara');
insert into customer (id, name, funds, type) values (174, 'George Stollen', 587, 'Trzebieszów');
insert into customer (id, name, funds, type) values (175, 'Tabbie Gumary', 755, 'Setono');
insert into customer (id, name, funds, type) values (176, 'Ellary Romayn', 585, 'Doksy');
insert into customer (id, name, funds, type) values (177, 'Tova Calderon', 252, 'Mirosławiec');
insert into customer (id, name, funds, type) values (178, 'Merrili Halle', 184, 'Zhulebino');
insert into customer (id, name, funds, type) values (179, 'Rogerio Browett', 471, 'Lenchwe Le Tau');
insert into customer (id, name, funds, type) values (180, 'Shay Rippin', 952, 'Xinquan');
insert into customer (id, name, funds, type) values (181, 'Mommy Videan', 880, 'Columbus');
insert into customer (id, name, funds, type) values (182, 'Maribelle Birdwistle', 134, 'Aksu');
insert into customer (id, name, funds, type) values (183, 'Dael Upcraft', 499, 'Queniquea');
insert into customer (id, name, funds, type) values (184, 'Geoffrey O''Hannigan', 864, 'Copa');
insert into customer (id, name, funds, type) values (185, 'Marybeth Tutt', 904, 'La Hacienda');
insert into customer (id, name, funds, type) values (186, 'Michaella Chatenier', 227, 'Khodzhi-Gasan');
insert into customer (id, name, funds, type) values (187, 'Sigismond Rojel', 943, 'Tamanan');
insert into customer (id, name, funds, type) values (188, 'Joann Howe', 431, 'Åtvidaberg');
insert into customer (id, name, funds, type) values (189, 'Cecilia Lackinton', 177, 'Quibdó');
insert into customer (id, name, funds, type) values (190, 'Pincas Morey', 678, 'Dapeng');
insert into customer (id, name, funds, type) values (191, 'Kali Penquet', 440, 'Ust’-Ulagan');
insert into customer (id, name, funds, type) values (192, 'Kimmi Manzell', 201, 'Klang');
insert into customer (id, name, funds, type) values (193, 'Guthrey Wishkar', 932, 'Huangzhuang');
insert into customer (id, name, funds, type) values (194, 'Glenn Hovell', 756, 'Loivos');
insert into customer (id, name, funds, type) values (195, 'Silvio Dumini', 237, 'Baizhang');
insert into customer (id, name, funds, type) values (196, 'Darnell Rockhall', 985, 'Qinjiang');
insert into customer (id, name, funds, type) values (197, 'Lilith Bushel', 159, 'Kamogatachō-kamogata');
insert into customer (id, name, funds, type) values (198, 'Alanah Buntain', 785, 'Yiliu');
insert into customer (id, name, funds, type) values (199, 'Doe Roullier', 430, 'Garoua');
insert into customer (id, name, funds, type) values (200, 'Millisent Radden', 202, 'Qianpai');
insert into customer (id, name, funds, type) values (201, 'Neely Cruickshank', 256, 'Flushing');
insert into customer (id, name, funds, type) values (202, 'Burk Ciobutaru', 53, 'Şaḩneh');
insert into customer (id, name, funds, type) values (203, 'Karlie Alderwick', 96, 'Aglipay');
insert into customer (id, name, funds, type) values (204, 'Lilli Robiou', 319, 'Novi Itebej');
insert into customer (id, name, funds, type) values (205, 'Sargent Schubuser', 533, 'Montecristi');
insert into customer (id, name, funds, type) values (206, 'Vernon Colebourne', 50, 'Bunda');
insert into customer (id, name, funds, type) values (207, 'Sanders Davidsson', 645, 'Kebonagung');
insert into customer (id, name, funds, type) values (208, 'Michaela De Michele', 868, 'Campo Quijano');
insert into customer (id, name, funds, type) values (209, 'Lynea Breakspear', 725, 'Suileng');
insert into customer (id, name, funds, type) values (210, 'Hermy Glancey', 368, 'Birigui');
insert into customer (id, name, funds, type) values (211, 'Isak Astill', 845, 'Basey');
insert into customer (id, name, funds, type) values (212, 'Jenifer Woodcraft', 135, 'Jiujiang');
insert into customer (id, name, funds, type) values (213, 'Genevieve Hamberstone', 117, 'Prakhon Chai');
insert into customer (id, name, funds, type) values (214, 'Yance Stoaks', 570, 'Ob’');
insert into customer (id, name, funds, type) values (215, 'Denyse Crannis', 996, 'Laguna Salada');
insert into customer (id, name, funds, type) values (216, 'Alejandrina Rimbault', 156, 'Ajoyani');
insert into customer (id, name, funds, type) values (217, 'Robenia Gerring', 607, 'Huicheng');
insert into customer (id, name, funds, type) values (218, 'Jackquelin Warder', 143, 'Barra do Garças');
insert into customer (id, name, funds, type) values (219, 'Leodora Milley', 94, 'Gelemso');
insert into customer (id, name, funds, type) values (220, 'Hieronymus Coffelt', 165, 'Hrastnik');
insert into customer (id, name, funds, type) values (221, 'Tann Blasio', 722, 'Matsue-shi');
insert into customer (id, name, funds, type) values (222, 'Gloriane Fewtrell', 998, 'Khānaqāh');
insert into customer (id, name, funds, type) values (223, 'Rick Villaron', 814, 'Pamplona/Iruña');
insert into customer (id, name, funds, type) values (224, 'Flemming Hadeke', 69, 'Yamoto');
insert into customer (id, name, funds, type) values (225, 'Kenyon Vizard', 425, 'Suicheng');
insert into customer (id, name, funds, type) values (226, 'Jeanna Denman', 327, 'Tempursari Wetan');
insert into customer (id, name, funds, type) values (227, 'Iolande Paolazzi', 817, 'Adrasmon');
insert into customer (id, name, funds, type) values (228, 'Salaidh Fielding', 766, 'Jiangyou');
insert into customer (id, name, funds, type) values (229, 'Clareta Fidelus', 699, 'Orong');
insert into customer (id, name, funds, type) values (230, 'Jay Teck', 2, 'San Vicente');
insert into customer (id, name, funds, type) values (231, 'Catriona Minichillo', 365, 'Lampa');
insert into customer (id, name, funds, type) values (232, 'Sybille Roubeix', 119, 'Massy');
insert into customer (id, name, funds, type) values (233, 'Nikki Mattaus', 44, 'Kangping');
insert into customer (id, name, funds, type) values (234, 'Erick Kmicicki', 275, 'Nikol’sk');
insert into customer (id, name, funds, type) values (235, 'Baxie Adamsky', 855, 'Chroustovice');
insert into customer (id, name, funds, type) values (236, 'Adan Howat', 116, 'Beihe');
insert into customer (id, name, funds, type) values (237, 'Anderea Caesar', 731, 'Comrat');
insert into customer (id, name, funds, type) values (238, 'Gerard Garrod', 115, 'Macha');
insert into customer (id, name, funds, type) values (239, 'Kyle Scatchard', 496, 'Helsingborg');
insert into customer (id, name, funds, type) values (240, 'Norrie Iskov', 694, 'Wenhe');
insert into customer (id, name, funds, type) values (241, 'Avery Leebetter', 406, 'Changlu');
insert into customer (id, name, funds, type) values (242, 'Joella Costa', 146, 'Xinli');
insert into customer (id, name, funds, type) values (243, 'Gard Ungaretti', 116, 'Nīshābūr');
insert into customer (id, name, funds, type) values (244, 'Pacorro De Souza', 573, 'Catriel');
insert into customer (id, name, funds, type) values (245, 'Yancy Gyse', 930, 'Damanhūr');
insert into customer (id, name, funds, type) values (246, 'Ogdon Haborn', 288, 'Sargodha');
insert into customer (id, name, funds, type) values (247, 'Othilie Rupprecht', 836, 'Janaka');
insert into customer (id, name, funds, type) values (248, 'Inna Heddan', 932, 'Strängnäs');
insert into customer (id, name, funds, type) values (249, 'Melly Nears', 529, 'Luboń');
insert into customer (id, name, funds, type) values (250, 'Patty Easterling', 849, 'Arauco');
insert into customer (id, name, funds, type) values (251, 'Katie Nice', 143, 'Ciseuseupan');
insert into customer (id, name, funds, type) values (252, 'Charlean Arlow', 133, 'Itaperuçu');
insert into customer (id, name, funds, type) values (253, 'Michale Duffin', 754, 'Ulyanovsk');
insert into customer (id, name, funds, type) values (254, 'Simeon Jaggard', 659, 'Santa Clara');
insert into customer (id, name, funds, type) values (255, 'Sauveur Levings', 956, 'Yanshou');
insert into customer (id, name, funds, type) values (256, 'Sigismund Zavattari', 590, 'Huiwen');
insert into customer (id, name, funds, type) values (257, 'Sebastian Regorz', 381, 'Cimongkor');
insert into customer (id, name, funds, type) values (258, 'Calhoun Denslow', 3, 'Chervonohryhorivka');
insert into customer (id, name, funds, type) values (259, 'Deny Godding', 657, 'Pirajuí');
insert into customer (id, name, funds, type) values (260, 'Padriac Gaish', 623, 'Danané');
insert into customer (id, name, funds, type) values (261, 'Lorelle Danko', 177, 'Sempu');
insert into customer (id, name, funds, type) values (262, 'Cathee Esplin', 854, 'Leiyang');
insert into customer (id, name, funds, type) values (263, 'Jaymie Pritchitt', 343, 'Kiełczów');
insert into customer (id, name, funds, type) values (264, 'Nathalie Ruf', 489, 'Trpinja');
insert into customer (id, name, funds, type) values (265, 'Kori Tiebe', 78, 'Paris 18');
insert into customer (id, name, funds, type) values (266, 'Matthiew Tonsley', 485, 'Kovilj');
insert into customer (id, name, funds, type) values (267, 'Jamima Heinsen', 814, 'São Paulo de Olivença');
insert into customer (id, name, funds, type) values (268, 'Bartolomeo Byrd', 662, 'El Carmen');
insert into customer (id, name, funds, type) values (269, 'Gillan Merkle', 168, 'Douarnenez');
insert into customer (id, name, funds, type) values (270, 'Raynard Mowen', 733, 'Lupak');
insert into customer (id, name, funds, type) values (271, 'Tades Jeremaes', 375, 'Rogowo');
insert into customer (id, name, funds, type) values (272, 'Tuck Simo', 132, 'Santos Dumont');
insert into customer (id, name, funds, type) values (273, 'Guglielmo Porch', 75, 'Ribeirão Preto');
insert into customer (id, name, funds, type) values (274, 'Dorolisa Caulder', 569, 'Ostrowite');
insert into customer (id, name, funds, type) values (275, 'Carmelle McCotter', 150, 'Nykarleby');
insert into customer (id, name, funds, type) values (276, 'Suzi Mitchenson', 484, 'Affery');
insert into customer (id, name, funds, type) values (277, 'Shelba Irvine', 640, 'Xiaojinkou');
insert into customer (id, name, funds, type) values (278, 'Shela McCrillis', 831, 'Cimalati');
insert into customer (id, name, funds, type) values (279, 'Arnie Croad', 633, 'Ózd');
insert into customer (id, name, funds, type) values (280, 'Gayleen Heliet', 186, 'Gongping');
insert into customer (id, name, funds, type) values (281, 'Man Brosetti', 158, 'Salzburg');
insert into customer (id, name, funds, type) values (282, 'Kelsey Luigi', 772, 'Rolândia');
insert into customer (id, name, funds, type) values (283, 'Matthieu Tupp', 301, 'Quilino');
insert into customer (id, name, funds, type) values (284, 'Mile Markham', 74, 'Datan');
insert into customer (id, name, funds, type) values (285, 'Percival Blewett', 35, 'Mananara');
insert into customer (id, name, funds, type) values (286, 'Torre Belderfield', 842, 'Veranópolis');
insert into customer (id, name, funds, type) values (287, 'Brig D''Arrigo', 301, 'Mülheim an der Ruhr');
insert into customer (id, name, funds, type) values (288, 'Aeriela Pietron', 589, 'Aga');
insert into customer (id, name, funds, type) values (289, 'Seward Kevis', 577, 'Konibodom');
insert into customer (id, name, funds, type) values (290, 'Camala Nathan', 307, 'Bel Air Rivière Sèche');
insert into customer (id, name, funds, type) values (291, 'Ellsworth Tomaini', 52, 'Igede-Ekiti');
insert into customer (id, name, funds, type) values (292, 'Ofilia Wadley', 209, 'Pavlovka');
insert into customer (id, name, funds, type) values (293, 'Rob Ravenshear', 990, 'Mouzourás');
insert into customer (id, name, funds, type) values (294, 'Aloysia Pordall', 261, 'Barabedang');
insert into customer (id, name, funds, type) values (295, 'Krishnah Coyett', 542, 'Phultala');
insert into customer (id, name, funds, type) values (296, 'Sharity Heggison', 868, 'El Crucero');
insert into customer (id, name, funds, type) values (297, 'Felipe Mabbot', 542, 'Malaya Dubna');
insert into customer (id, name, funds, type) values (298, 'Allyson Pexton', 708, 'Dadiya');
insert into customer (id, name, funds, type) values (299, 'Lib Stonhard', 681, 'Kikinda');
insert into customer (id, name, funds, type) values (300, 'Miles Steinham', 676, 'Miłosław');
insert into customer (id, name, funds, type) values (301, 'Lusa Skottle', 585, 'Banjar Tegal Belodan');
insert into customer (id, name, funds, type) values (302, 'Georgia Muxworthy', 528, 'Qila Abdullāh');
insert into customer (id, name, funds, type) values (303, 'Burlie Gentil', 121, 'Sukadana');
insert into customer (id, name, funds, type) values (304, 'Baron Chate', 536, 'Catbalogan');
insert into customer (id, name, funds, type) values (305, 'Nealon Piborn', 521, 'Laugar');
insert into customer (id, name, funds, type) values (306, 'Wang Addekin', 795, 'Tadianjie');
insert into customer (id, name, funds, type) values (307, 'Ansley D''Acth', 322, 'Hotaka');
insert into customer (id, name, funds, type) values (308, 'Sisely Grubbe', 65, 'Gunungkendeng');
insert into customer (id, name, funds, type) values (309, 'Dael Beverage', 599, 'Mellila');
insert into customer (id, name, funds, type) values (310, 'Kirstyn Sargood', 529, 'Severka');
insert into customer (id, name, funds, type) values (311, 'Torey Lynnitt', 649, 'Anyuan');
insert into customer (id, name, funds, type) values (312, 'Wenda Kupis', 374, 'Marseille');
insert into customer (id, name, funds, type) values (313, 'Feodor Drohun', 787, 'Riđica');
insert into customer (id, name, funds, type) values (314, 'Julie Gowdridge', 569, 'Phú Lộc');
insert into customer (id, name, funds, type) values (315, 'Chick Peaker', 204, 'Santiago');
insert into customer (id, name, funds, type) values (316, 'Leland Goucher', 424, 'Roche-à-Bateau');
insert into customer (id, name, funds, type) values (317, 'Alfi Darling', 976, 'Surgut');
insert into customer (id, name, funds, type) values (318, 'Brennen Prater', 460, 'Gongchang');
insert into customer (id, name, funds, type) values (319, 'Miller Tilberry', 226, 'Lomba do Loução');
insert into customer (id, name, funds, type) values (320, 'Alexandro Govan', 484, 'Magisterial');
insert into customer (id, name, funds, type) values (321, 'Bobbye Turfin', 691, 'Anyuan');
insert into customer (id, name, funds, type) values (322, 'Wanids Tanser', 199, 'Duisburg');
insert into customer (id, name, funds, type) values (323, 'Vinita Aubray', 941, 'Firmat');
insert into customer (id, name, funds, type) values (324, 'Sascha Brusin', 861, 'Tai Po');
insert into customer (id, name, funds, type) values (325, 'Findley Attoe', 627, 'Chor');
insert into customer (id, name, funds, type) values (326, 'Wolfie Andriolli', 132, 'Kumanovo');
insert into customer (id, name, funds, type) values (327, 'Leeland Attride', 690, 'Catu');
insert into customer (id, name, funds, type) values (328, 'Milena Marston', 744, 'Calheta');
insert into customer (id, name, funds, type) values (329, 'Chaunce Grichukhanov', 423, 'Laval');
insert into customer (id, name, funds, type) values (330, 'Cora Altoft', 74, 'Czeremcha');
insert into customer (id, name, funds, type) values (331, 'Judah Warboys', 521, 'Kolirerek');
insert into customer (id, name, funds, type) values (332, 'Juan Meatcher', 791, 'Leiwang');
insert into customer (id, name, funds, type) values (333, 'Waring Narrie', 294, 'Rybinsk');
insert into customer (id, name, funds, type) values (334, 'Krisha Fletcher', 790, 'Czarków');
insert into customer (id, name, funds, type) values (335, 'Darrell Nairns', 977, 'Cikaung');
insert into customer (id, name, funds, type) values (336, 'Lanny Coiley', 180, 'Morrinhos');
insert into customer (id, name, funds, type) values (337, 'Lolly Willison', 922, 'Svojat');
insert into customer (id, name, funds, type) values (338, 'Sholom Bengoechea', 486, 'Emiliano Zapata');
insert into customer (id, name, funds, type) values (339, 'Ebeneser Tennison', 832, 'Muḩradah');
insert into customer (id, name, funds, type) values (340, 'Carri Cours', 333, 'Nadvoitsy');
insert into customer (id, name, funds, type) values (341, 'Storm Defond', 260, 'Tanashichō');
insert into customer (id, name, funds, type) values (342, 'Katrine Domotor', 446, 'Dianbu');
insert into customer (id, name, funds, type) values (343, 'Boot Beddoes', 727, 'El Retén');
insert into customer (id, name, funds, type) values (344, 'Margret Lantaff', 359, 'Qianjiang');
insert into customer (id, name, funds, type) values (345, 'Kelsy Idale', 925, 'Skoghall');
insert into customer (id, name, funds, type) values (346, 'Serena Larchier', 20, 'Itaituba');
insert into customer (id, name, funds, type) values (347, 'Monika Vigars', 945, 'Bobonan');
insert into customer (id, name, funds, type) values (348, 'Leela Kelwaybamber', 402, 'Taungdwingyi');
insert into customer (id, name, funds, type) values (349, 'Maria Drayson', 930, 'Passos');
insert into customer (id, name, funds, type) values (350, 'Leesa Doward', 483, 'Suntar');
insert into customer (id, name, funds, type) values (351, 'Denni Warlton', 284, 'Caringin Lor');
insert into customer (id, name, funds, type) values (352, 'Robbyn Manchester', 240, 'Kiuola');
insert into customer (id, name, funds, type) values (353, 'Skell Gabel', 922, 'Bochum');
insert into customer (id, name, funds, type) values (354, 'David Ellicock', 143, 'Digne-les-Bains');
insert into customer (id, name, funds, type) values (355, 'Margit Furse', 174, 'Salaš Crnobarski');
insert into customer (id, name, funds, type) values (356, 'Orland Lanney', 770, 'Barmash');
insert into customer (id, name, funds, type) values (357, 'Arabella Eburah', 88, 'Cigintung');
insert into customer (id, name, funds, type) values (358, 'Zollie Fontell', 3, '5 de Mayo');
insert into customer (id, name, funds, type) values (359, 'Rickard Jorcke', 100, 'El Mida');
insert into customer (id, name, funds, type) values (360, 'Candy Downing', 59, 'Lazaro Cardenas');
insert into customer (id, name, funds, type) values (361, 'Gwen Sawkin', 38, 'Matatiele');
insert into customer (id, name, funds, type) values (362, 'Yevette Kemwal', 230, 'Lebane');
insert into customer (id, name, funds, type) values (363, 'Alfons Breckin', 30, 'Hujirt');
insert into customer (id, name, funds, type) values (364, 'Jessalyn Prettjohn', 205, 'Zhongdeng');
insert into customer (id, name, funds, type) values (365, 'Huntley Pleasaunce', 122, 'Trindade');
insert into customer (id, name, funds, type) values (366, 'Ruthie Shaves', 192, 'Huangqi');
insert into customer (id, name, funds, type) values (367, 'Justin Kennerknecht', 830, 'Zhugentan');
insert into customer (id, name, funds, type) values (368, 'Wayland Allmen', 652, 'Novoanninskiy');
insert into customer (id, name, funds, type) values (369, 'Myles Haggerstone', 989, 'Sovetskaya Gavan’');
insert into customer (id, name, funds, type) values (370, 'Lemar Padula', 686, 'Ketampak');
insert into customer (id, name, funds, type) values (371, 'Roberto Zealey', 530, 'Buenavista');
insert into customer (id, name, funds, type) values (372, 'Cordula Cutridge', 938, 'Guarujá');
insert into customer (id, name, funds, type) values (373, 'Carlie Dudman', 915, 'Velký Týnec');
insert into customer (id, name, funds, type) values (374, 'Kerrill Kingsford', 742, 'Norrköping');
insert into customer (id, name, funds, type) values (375, 'Merrielle Karpushkin', 572, 'Yakovlevo');
insert into customer (id, name, funds, type) values (376, 'Sherwynd Bellow', 106, 'Kaytitinga');
insert into customer (id, name, funds, type) values (377, 'Tabbitha Weale', 889, 'Vřesina');
insert into customer (id, name, funds, type) values (378, 'Jud Leirmonth', 142, 'Pueblo Nuevo');
insert into customer (id, name, funds, type) values (379, 'Aylmar Seel', 363, 'Mrozy');
insert into customer (id, name, funds, type) values (380, 'Darya Rudloff', 737, 'Banocboc');
insert into customer (id, name, funds, type) values (381, 'Helyn Goddard', 260, 'El Obeid');
insert into customer (id, name, funds, type) values (382, 'Teddie Tudge', 508, 'Jinshanzui');
insert into customer (id, name, funds, type) values (383, 'Kearney Longbone', 746, 'Sergeyevka');
insert into customer (id, name, funds, type) values (384, 'Guilbert Guerrazzi', 297, 'Qŭrghontepa');
insert into customer (id, name, funds, type) values (385, 'Ame Lamburne', 845, 'Rio Covo');
insert into customer (id, name, funds, type) values (386, 'Esra Iacopetti', 982, 'Birqīn');
insert into customer (id, name, funds, type) values (387, 'Henrik Passler', 814, 'Pärnu-Jaagupi');
insert into customer (id, name, funds, type) values (388, 'Loni Pluthero', 808, 'Desa Werasari');
insert into customer (id, name, funds, type) values (389, 'Julius Ketteridge', 465, 'Santo Tomas');
insert into customer (id, name, funds, type) values (390, 'Ezekiel Jaslem', 179, 'Krutinka');
insert into customer (id, name, funds, type) values (391, 'Jo-ann Tomeo', 817, 'Staten Island');
insert into customer (id, name, funds, type) values (392, 'Valdemar Stallwood', 982, 'Xiaojia');
insert into customer (id, name, funds, type) values (393, 'North Teacy', 941, 'Sollefteå');
insert into customer (id, name, funds, type) values (394, 'Laural Wandrach', 788, 'Jinhai');
insert into customer (id, name, funds, type) values (395, 'Carmelina Moyser', 293, 'Pasirputih');
insert into customer (id, name, funds, type) values (396, 'Selie Howe', 409, 'Nioro du Rip');
insert into customer (id, name, funds, type) values (397, 'Darryl Masden', 303, 'Hīsh');
insert into customer (id, name, funds, type) values (398, 'Bondy Olivet', 506, 'Ciparay');
insert into customer (id, name, funds, type) values (399, 'Tessie Patria', 959, 'Riangbao');
insert into customer (id, name, funds, type) values (400, 'Dix Yoakley', 176, 'Glagahan');
insert into customer (id, name, funds, type) values (401, 'Agustin Cleyne', 1, 'Lubień Kujawski');
insert into customer (id, name, funds, type) values (402, 'Monte Luisetti', 876, 'Остров Пасхи');
insert into customer (id, name, funds, type) values (403, 'Brittaney Knowlman', 84, 'Cochrane');
insert into customer (id, name, funds, type) values (404, 'Kylie Stebbings', 300, 'Jianshe');
insert into customer (id, name, funds, type) values (405, 'Elspeth Rollins', 260, 'Bodø');
insert into customer (id, name, funds, type) values (406, 'Quincy Deller', 17, 'Belfort');
insert into customer (id, name, funds, type) values (407, 'Caye Nisot', 433, 'Bantay');
insert into customer (id, name, funds, type) values (408, 'Nappy Glaum', 37, 'Rudnik');
insert into customer (id, name, funds, type) values (409, 'Hoyt Recher', 606, 'Valencia');
insert into customer (id, name, funds, type) values (410, 'Desirae O''Lynn', 149, 'Zhongshanlu');
insert into customer (id, name, funds, type) values (411, 'Daven Nekrews', 804, 'Hangbu');
insert into customer (id, name, funds, type) values (412, 'Wallace Elsbury', 529, 'Karolinka');
insert into customer (id, name, funds, type) values (413, 'Kahaleel Asbury', 20, 'Kambove');
insert into customer (id, name, funds, type) values (414, 'Norry Queen', 577, 'Babakan');
insert into customer (id, name, funds, type) values (415, 'Bryn Britton', 69, 'Kosamphi Nakhon');
insert into customer (id, name, funds, type) values (416, 'Lazaro Hacard', 489, 'Newport News');
insert into customer (id, name, funds, type) values (417, 'Ambrosius Ioannou', 674, 'Chikan');
insert into customer (id, name, funds, type) values (418, 'Graeme Gilliver', 575, 'Benito Juarez');
insert into customer (id, name, funds, type) values (419, 'Ferguson Lindner', 807, 'Chicama');
insert into customer (id, name, funds, type) values (420, 'Hermia Drance', 684, 'Mongo');
insert into customer (id, name, funds, type) values (421, 'Kettie Butland', 933, 'Wasquehal');
insert into customer (id, name, funds, type) values (422, 'Lennie Crudge', 780, 'Las Palmas');
insert into customer (id, name, funds, type) values (423, 'Rodolph Pither', 334, 'Trångsund');
insert into customer (id, name, funds, type) values (424, 'Danit Milroy', 30, 'São Roque');
insert into customer (id, name, funds, type) values (425, 'Major Peele', 396, 'Changsha');
insert into customer (id, name, funds, type) values (426, 'Brose Spur', 83, 'Bao’an');
insert into customer (id, name, funds, type) values (427, 'Dory Peirce', 766, 'Sukošan');
insert into customer (id, name, funds, type) values (428, 'Cello Clemanceau', 660, 'San José');
insert into customer (id, name, funds, type) values (429, 'Allen Rate', 72, 'Lillooet');
insert into customer (id, name, funds, type) values (430, 'Siusan Gilloran', 852, 'Suntar');
insert into customer (id, name, funds, type) values (431, 'Ladonna Conrard', 50, 'Rennes');
insert into customer (id, name, funds, type) values (432, 'Elane Housiaux', 245, 'Washington');
insert into customer (id, name, funds, type) values (433, 'Francklin Friedlos', 43, 'Lingbeizhou');
insert into customer (id, name, funds, type) values (434, 'Sullivan Pellman', 555, 'Umeå');
insert into customer (id, name, funds, type) values (435, 'Rianon Dominique', 609, 'Rodas');
insert into customer (id, name, funds, type) values (436, 'Huberto Edgeon', 79, 'Mailsi');
insert into customer (id, name, funds, type) values (437, 'Francine Martelet', 987, 'Fengtai');
insert into customer (id, name, funds, type) values (438, 'Glynda Garrattley', 93, 'Eling');
insert into customer (id, name, funds, type) values (439, 'Pyotr Streather', 269, 'Арачиново');
insert into customer (id, name, funds, type) values (440, 'Angelika Pickavance', 818, 'Ōarai');
insert into customer (id, name, funds, type) values (441, 'Anton Officer', 82, 'Lugang');
insert into customer (id, name, funds, type) values (442, 'Ebenezer McClory', 124, 'Alibunan');
insert into customer (id, name, funds, type) values (443, 'Penny Hanscomb', 128, 'Tochio-honchō');
insert into customer (id, name, funds, type) values (444, 'Aubrey Perche', 103, 'Hovtashen');
insert into customer (id, name, funds, type) values (445, 'Alison Mantz', 644, 'Narbonne');
insert into customer (id, name, funds, type) values (446, 'Tiertza Linnit', 693, 'Goiás');
insert into customer (id, name, funds, type) values (447, 'Georgeanna Joyes', 426, 'Oropéndolas');
insert into customer (id, name, funds, type) values (448, 'Adelina Mellmer', 31, 'Reriz');
insert into customer (id, name, funds, type) values (449, 'Erick Randerson', 915, 'Tomohon');
insert into customer (id, name, funds, type) values (450, 'Wendi McQuirk', 65, 'Dhali');
insert into customer (id, name, funds, type) values (451, 'Ichabod Buntin', 198, 'Wahang Dua');
insert into customer (id, name, funds, type) values (452, 'Alexandros Hegley', 734, 'Lianhua');
insert into customer (id, name, funds, type) values (453, 'Marylinda Shuttleworth', 772, 'Ciudad Sandino');
insert into customer (id, name, funds, type) values (454, 'Sherman Grigs', 429, 'Youfang');
insert into customer (id, name, funds, type) values (455, 'Aurie Eates', 892, 'Doropayung');
insert into customer (id, name, funds, type) values (456, 'Jess Rieme', 815, 'Molde');
insert into customer (id, name, funds, type) values (457, 'Natale Trewett', 451, 'Xiaojing');
insert into customer (id, name, funds, type) values (458, 'Odie Hing', 403, 'Santa Rosa');
insert into customer (id, name, funds, type) values (459, 'Hewitt Calcutt', 580, 'Kill');
insert into customer (id, name, funds, type) values (460, 'Isidore Caudwell', 27, 'Tisul’');
insert into customer (id, name, funds, type) values (461, 'Victoir Storrs', 910, 'Barra');
insert into customer (id, name, funds, type) values (462, 'Derry Foyle', 568, 'Scottsdale');
insert into customer (id, name, funds, type) values (463, 'Eve Bedinn', 92, 'Ayapel');
insert into customer (id, name, funds, type) values (464, 'Vi Danes', 464, 'Raglan');
insert into customer (id, name, funds, type) values (465, 'Friedrick Geekin', 990, 'Argenteuil');
insert into customer (id, name, funds, type) values (466, 'Gunther Simenet', 348, 'Zhanggongmiao');
insert into customer (id, name, funds, type) values (467, 'Tobie Hartnell', 42, 'Manzanares');
insert into customer (id, name, funds, type) values (468, 'Caron Benning', 739, 'Jawl al Majma‘');
insert into customer (id, name, funds, type) values (469, 'Annalise Harbisher', 33, 'Sodankylä');
insert into customer (id, name, funds, type) values (470, 'Noam Duferie', 817, 'Smolenka');
insert into customer (id, name, funds, type) values (471, 'Ashlen Neubigging', 188, 'Ban Houayxay');
insert into customer (id, name, funds, type) values (472, 'Fidelia Coupland', 653, 'Guanshan');
insert into customer (id, name, funds, type) values (473, 'Agnes Blatherwick', 229, 'Qujiang');
insert into customer (id, name, funds, type) values (474, 'Gerladina Petkens', 700, 'Huayuan');
insert into customer (id, name, funds, type) values (475, 'Maury Graveney', 615, 'Vouani');
insert into customer (id, name, funds, type) values (476, 'Jule Cribbott', 285, 'Votuporanga');
insert into customer (id, name, funds, type) values (477, 'Korie Lydford', 183, 'Tol’yatti');
insert into customer (id, name, funds, type) values (478, 'Gusella Abramcik', 185, 'São Lourenço do Sul');
insert into customer (id, name, funds, type) values (479, 'Donaugh Gowanson', 470, 'Saubara');
insert into customer (id, name, funds, type) values (480, 'Wallache Overthrow', 675, 'Oshawa');
insert into customer (id, name, funds, type) values (481, 'Harlie McAneny', 685, 'Comodoro Rivadavia');
insert into customer (id, name, funds, type) values (482, 'Stevie Crampsey', 285, 'Rimba Sekampung');
insert into customer (id, name, funds, type) values (483, 'Corabelle Longforth', 782, 'Alah Sāy');
insert into customer (id, name, funds, type) values (484, 'Niles Aronov', 438, 'Xinfang');
insert into customer (id, name, funds, type) values (485, 'Jill Allsworth', 459, 'Villa Ocampo');
insert into customer (id, name, funds, type) values (486, 'Roxanna Cicullo', 540, 'Montaneza');
insert into customer (id, name, funds, type) values (487, 'Collette O''Scanlon', 212, 'Ad Dilam');
insert into customer (id, name, funds, type) values (488, 'Winona Cartmael', 785, 'Beiqijia');
insert into customer (id, name, funds, type) values (489, 'Bentley Pointin', 349, 'Macari');
insert into customer (id, name, funds, type) values (490, 'Anthea Spyvye', 817, 'Seget');
insert into customer (id, name, funds, type) values (491, 'Donnamarie Loges', 926, 'La Garenne-Colombes');
insert into customer (id, name, funds, type) values (492, 'Jenni Domniney', 993, 'Tsingoni');
insert into customer (id, name, funds, type) values (493, 'Addy Gooder', 329, 'São Bartolomeu');
insert into customer (id, name, funds, type) values (494, 'Robinet Mottinelli', 688, 'Orsk');
insert into customer (id, name, funds, type) values (495, 'Orelle Beinke', 854, 'Tenja');
insert into customer (id, name, funds, type) values (496, 'Rachel Collcott', 860, 'Lingtou');
insert into customer (id, name, funds, type) values (497, 'Joscelin Burgess', 338, 'Tam Bình');
insert into customer (id, name, funds, type) values (498, 'Herman Vanyarkin', 25, 'Kosino');
insert into customer (id, name, funds, type) values (499, 'Hinda Lefeuvre', 840, 'Nueva Arica');
insert into customer (id, name, funds, type) values (500, 'Aurlie Daunay', 390, 'Khān Shaykhūn');
insert into customer (id, name, funds, type) values (501, 'Gerardo Boggers', 391, 'Bojonggenteng');
insert into customer (id, name, funds, type) values (502, 'Rhea Eyckelberg', 826, 'Morelos');
insert into customer (id, name, funds, type) values (503, 'Lisle Sapey', 33, 'Memphis');
insert into customer (id, name, funds, type) values (504, 'Mauricio Andreini', 379, 'Baler Baleagung');
insert into customer (id, name, funds, type) values (505, 'Codee Smithen', 203, 'Kosiv');
insert into customer (id, name, funds, type) values (506, 'Milly Mowett', 629, 'Sacramento');
insert into customer (id, name, funds, type) values (507, 'Dagmar Ashforth', 831, 'Bromma');
insert into customer (id, name, funds, type) values (508, 'Ingmar McQuillen', 738, 'Fanyang');
insert into customer (id, name, funds, type) values (509, 'Deirdre Stainburn', 848, 'Turbo');
insert into customer (id, name, funds, type) values (510, 'Myranda Ibeson', 664, 'Biris Daja');
insert into customer (id, name, funds, type) values (511, 'Normand Kippax', 595, 'Somba');
insert into customer (id, name, funds, type) values (512, 'Deerdre Povele', 914, 'Zhu’ao');
insert into customer (id, name, funds, type) values (513, 'Olva Bagniuk', 544, 'Shixi');
insert into customer (id, name, funds, type) values (514, 'Faydra Tenpenny', 218, 'Sara Kunda');
insert into customer (id, name, funds, type) values (515, 'Edi Knappe', 313, 'Évreux');
insert into customer (id, name, funds, type) values (516, 'Karalee Hudson', 224, 'Nikísiani');
insert into customer (id, name, funds, type) values (517, 'Grissel Marland', 548, 'Daxi');
insert into customer (id, name, funds, type) values (518, 'Robinia Hammerman', 385, 'Tall Abyaḑ');
insert into customer (id, name, funds, type) values (519, 'Mona O''Crigan', 33, 'Aengceleng');
insert into customer (id, name, funds, type) values (520, 'Hermia McNerlin', 66, 'Santa Rosa');
insert into customer (id, name, funds, type) values (521, 'Russ Carlozzi', 984, 'Rokem Barat');
insert into customer (id, name, funds, type) values (522, 'Jacintha Kettridge', 543, 'Sobral');
insert into customer (id, name, funds, type) values (523, 'Quintus Lammin', 854, 'Monjarás');
insert into customer (id, name, funds, type) values (524, 'Aurthur Lannen', 978, 'Dofa');
insert into customer (id, name, funds, type) values (525, 'Dominique Meadowcraft', 902, 'Georgetown');
insert into customer (id, name, funds, type) values (526, 'Felecia Blann', 662, 'Praia Grande');
insert into customer (id, name, funds, type) values (527, 'Abagail Dagworthy', 858, 'Sokarame');
insert into customer (id, name, funds, type) values (528, 'Salvidor Pitrollo', 318, 'Piraju');
insert into customer (id, name, funds, type) values (529, 'Elnar Cranmer', 109, 'Meijiahe');
insert into customer (id, name, funds, type) values (530, 'Godfree Deyes', 818, 'Kaiama');
insert into customer (id, name, funds, type) values (531, 'Mackenzie Eplate', 868, 'Kostino');
insert into customer (id, name, funds, type) values (532, 'Valery Lattos', 296, 'Kapinango');
insert into customer (id, name, funds, type) values (533, 'Kirby Tunnoch', 482, 'Khlong Yai');
insert into customer (id, name, funds, type) values (534, 'Burgess Minchinden', 835, 'Rokitno Szlacheckie');
insert into customer (id, name, funds, type) values (535, 'Rafa Donson', 757, 'Kurlovo');
insert into customer (id, name, funds, type) values (536, 'Olimpia Pauletto', 805, 'Lębork');
insert into customer (id, name, funds, type) values (537, 'Nollie Anlay', 620, 'Lemenhe');
insert into customer (id, name, funds, type) values (538, 'Gracie Tierny', 34, 'Oslo');
insert into customer (id, name, funds, type) values (539, 'Faustine Canter', 714, 'Paiisa');
insert into customer (id, name, funds, type) values (540, 'Marjy Pinnere', 209, 'Sukhirin');
insert into customer (id, name, funds, type) values (541, 'Rochester Eastham', 522, 'Longtang');
insert into customer (id, name, funds, type) values (542, 'Maitilde Greatrex', 32, 'Clondalkin');
insert into customer (id, name, funds, type) values (543, 'Rick MacKomb', 341, 'Maniowy');
insert into customer (id, name, funds, type) values (544, 'Mari O''Beirne', 916, 'Chengdong');
insert into customer (id, name, funds, type) values (545, 'Aldon Farquharson', 494, 'Nghi Xuân');
insert into customer (id, name, funds, type) values (546, 'Arden Stovold', 331, 'Rochester');
insert into customer (id, name, funds, type) values (547, 'Randene Gwinn', 54, 'Maonon');
insert into customer (id, name, funds, type) values (548, 'Audrie Klemencic', 269, 'Katsina-Ala');
insert into customer (id, name, funds, type) values (549, 'Mel Aimeric', 736, 'Mella');
insert into customer (id, name, funds, type) values (550, 'Ashleigh Lloyd-Williams', 195, 'Sorinomo');
insert into customer (id, name, funds, type) values (551, 'Gusta McKibbin', 345, 'Poponcol');
insert into customer (id, name, funds, type) values (552, 'Gabbie Blayney', 166, 'Erétria');
insert into customer (id, name, funds, type) values (553, 'Elvina Yurivtsev', 772, 'Catbalogan');
insert into customer (id, name, funds, type) values (554, 'Jeddy Goldes', 846, 'Haridimun');
insert into customer (id, name, funds, type) values (555, 'Rebe MacDonnell', 359, 'Avanca');
insert into customer (id, name, funds, type) values (556, 'Niven Barkworth', 532, 'Kyzyldzhar');
insert into customer (id, name, funds, type) values (557, 'Valentina Corstan', 936, 'Pucyura');
insert into customer (id, name, funds, type) values (558, 'Lorens O''Hagirtie', 178, 'Verkhov’ye');
insert into customer (id, name, funds, type) values (559, 'Gustave Barnfather', 563, 'Samanco');
insert into customer (id, name, funds, type) values (560, 'Artemus Baiss', 197, 'Kortesjärvi');
insert into customer (id, name, funds, type) values (561, 'Allister Minette', 127, 'Osek nad Bečvou');
insert into customer (id, name, funds, type) values (562, 'Tome Roche', 261, 'Bayan Qagan');
insert into customer (id, name, funds, type) values (563, 'Abba Lafrentz', 915, 'Saint-Paul');
insert into customer (id, name, funds, type) values (564, 'Annamaria Harse', 818, 'Mitú');
insert into customer (id, name, funds, type) values (565, 'Jessi Dalzell', 580, 'Yongchang');
insert into customer (id, name, funds, type) values (566, 'Virginia Kennermann', 478, 'Ḩarf al Musaytirah');
insert into customer (id, name, funds, type) values (567, 'Garrard Alderton', 151, 'Krychaw');
insert into customer (id, name, funds, type) values (568, 'Emmet O''Giany', 979, 'Tabango');
insert into customer (id, name, funds, type) values (569, 'Merrill Kryzhov', 344, 'Duoxiang');
insert into customer (id, name, funds, type) values (570, 'Rayner McNaught', 930, 'Gaojia');
insert into customer (id, name, funds, type) values (571, 'Marylinda Cruces', 909, 'Infantas');
insert into customer (id, name, funds, type) values (572, 'Larina Hrinchishin', 894, 'Huiyuan');
insert into customer (id, name, funds, type) values (573, 'Lauraine Cappel', 446, 'Mas‘adah');
insert into customer (id, name, funds, type) values (574, 'Cassie Oertzen', 626, 'Doubravice nad Svitavou');
insert into customer (id, name, funds, type) values (575, 'Selig Attew', 738, 'Norcasia');
insert into customer (id, name, funds, type) values (576, 'Sigfrid Chasles', 661, 'Vanáton');
insert into customer (id, name, funds, type) values (577, 'Quinn Stockey', 951, 'Gabasumdo');
insert into customer (id, name, funds, type) values (578, 'Cymbre Barkes', 655, 'Hengxianhe');
insert into customer (id, name, funds, type) values (579, 'Cyrill Stubbins', 883, 'Kandun');
insert into customer (id, name, funds, type) values (580, 'Mia Pitrasso', 995, 'Daxbet');
insert into customer (id, name, funds, type) values (581, 'Cesaro Rosedale', 78, 'Saratamata');
insert into customer (id, name, funds, type) values (582, 'Fabiano Plumbridge', 598, 'Jingling');
insert into customer (id, name, funds, type) values (583, 'Ginevra Spellesy', 57, 'Bechlín');
insert into customer (id, name, funds, type) values (584, 'Dalli Mixon', 528, 'Gunung Talang');
insert into customer (id, name, funds, type) values (585, 'Aubree Mazdon', 386, 'Shuitou');
insert into customer (id, name, funds, type) values (586, 'Joyous Giovannacci', 573, 'Krapina');
insert into customer (id, name, funds, type) values (587, 'Jessey Girardi', 708, 'Kangping');
insert into customer (id, name, funds, type) values (588, 'Harriot de Glanville', 100, 'Gemuruh');
insert into customer (id, name, funds, type) values (589, 'Claude Suermeier', 56, 'Yumbel');
insert into customer (id, name, funds, type) values (590, 'Humfrey Milmore', 447, 'Kālia');
insert into customer (id, name, funds, type) values (591, 'Parker Hunnawill', 454, 'Brades');
insert into customer (id, name, funds, type) values (592, 'Karin Pury', 599, 'Lokosovo');
insert into customer (id, name, funds, type) values (593, 'Tabina Deny', 474, 'Kembangarum');
insert into customer (id, name, funds, type) values (594, 'Beverie Fowles', 838, 'Kingston');
insert into customer (id, name, funds, type) values (595, 'Garfield Fulcher', 472, 'Bacabal');
insert into customer (id, name, funds, type) values (596, 'Adora Yanshinov', 878, 'Prostřední Bečva');
insert into customer (id, name, funds, type) values (597, 'Glory Cullity', 311, 'Santa Praxedes');
insert into customer (id, name, funds, type) values (598, 'Ezekiel Giacomuzzo', 648, 'Niamtougou');
insert into customer (id, name, funds, type) values (599, 'Rodger Tincey', 185, 'Abu Dhabi');
insert into customer (id, name, funds, type) values (600, 'Ginger Treadgall', 623, 'Breves');
insert into customer (id, name, funds, type) values (601, 'Sharia De Francesco', 680, 'Xincheng');
insert into customer (id, name, funds, type) values (602, 'Tani Shippey', 442, 'Maguan');
insert into customer (id, name, funds, type) values (603, 'Alastair Bleby', 587, 'Yylanly');
insert into customer (id, name, funds, type) values (604, 'Libbie Pechold', 377, 'Yilongyong');
insert into customer (id, name, funds, type) values (605, 'Husain McKleod', 972, 'Constance');
insert into customer (id, name, funds, type) values (606, 'Cindie Blatherwick', 241, 'Nelas');
insert into customer (id, name, funds, type) values (607, 'Klara Tynan', 777, 'Kavásilas');
insert into customer (id, name, funds, type) values (608, 'Gray Tollmache', 774, 'Kansas City');
insert into customer (id, name, funds, type) values (609, 'Auguste Garretts', 423, 'Linton');
insert into customer (id, name, funds, type) values (610, 'Sophey Andreaccio', 879, 'Huité');
insert into customer (id, name, funds, type) values (611, 'Franny Van Hault', 158, 'Shirochanka');
insert into customer (id, name, funds, type) values (612, 'Krystyna Matuskiewicz', 540, 'Cangkeuteuk Sabrang');
insert into customer (id, name, funds, type) values (613, 'Neely Vannuchi', 808, 'Isla Verde');
insert into customer (id, name, funds, type) values (614, 'Jaye Marzella', 722, 'Turki');
insert into customer (id, name, funds, type) values (615, 'Alard Ranshaw', 84, 'Jinchang');
insert into customer (id, name, funds, type) values (616, 'Fanechka Whifen', 171, 'Sulūk');
insert into customer (id, name, funds, type) values (617, 'Laney Bolley', 649, 'Dom Pedrito');
insert into customer (id, name, funds, type) values (618, 'Eddy Whiten', 455, 'Zhangbagou');
insert into customer (id, name, funds, type) values (619, 'Channa Edmonds', 782, 'San Agustín Acasaguastlán');
insert into customer (id, name, funds, type) values (620, 'Rich O''Sheerin', 939, 'Wonorejo Dua');
insert into customer (id, name, funds, type) values (621, 'Sibby Ruggieri', 506, 'Chitral');
insert into customer (id, name, funds, type) values (622, 'Frederic Marcinkowski', 936, 'Cengang');
insert into customer (id, name, funds, type) values (623, 'Isa Avraam', 339, 'Château-Richer');
insert into customer (id, name, funds, type) values (624, 'Guenna Goult', 100, 'Visby');
insert into customer (id, name, funds, type) values (625, 'Clemmie Kassidy', 878, 'Chaiwan');
insert into customer (id, name, funds, type) values (626, 'De Scanlin', 535, 'Itiruçu');
insert into customer (id, name, funds, type) values (627, 'Jacobo Peppett', 794, 'Trzciana');
insert into customer (id, name, funds, type) values (628, 'Fred Poinsett', 269, 'Prabuty');
insert into customer (id, name, funds, type) values (629, 'Joeann Harle', 795, 'Parelhas');
insert into customer (id, name, funds, type) values (630, 'Kathy Ownsworth', 654, 'Pasirlaja');
insert into customer (id, name, funds, type) values (631, 'Reynold Hylands', 76, 'Suvorovo');
insert into customer (id, name, funds, type) values (632, 'Emmott Burl', 412, 'Barrancabermeja');
insert into customer (id, name, funds, type) values (633, 'Estel O''Beirne', 391, 'Um Jar Al Gharbiyya');
insert into customer (id, name, funds, type) values (634, 'Sharline Peel', 463, 'Rufino');
insert into customer (id, name, funds, type) values (635, 'Latia Sola', 994, 'Inhumas');
insert into customer (id, name, funds, type) values (636, 'Averill Bearblock', 845, 'Karkkila');
insert into customer (id, name, funds, type) values (637, 'Sherwin Mynett', 274, 'Rio Piracicaba');
insert into customer (id, name, funds, type) values (638, 'Tedi Silkston', 636, 'Xiyuan');
insert into customer (id, name, funds, type) values (639, 'Idell Goward', 715, 'Botou');
insert into customer (id, name, funds, type) values (640, 'Ruy Bromfield', 396, 'Kawm Umbū');
insert into customer (id, name, funds, type) values (641, 'Evin Leaman', 435, 'Dahedian');
insert into customer (id, name, funds, type) values (642, 'Evvy Mountain', 344, 'Colorado Springs');
insert into customer (id, name, funds, type) values (643, 'Daniel Dureden', 783, 'Wonokerto');
insert into customer (id, name, funds, type) values (644, 'Ania Burchard', 195, 'Bureng');
insert into customer (id, name, funds, type) values (645, 'Robenia Shipston', 97, 'Umm Ruwaba');
insert into customer (id, name, funds, type) values (646, 'Bary Kleimt', 912, 'Şuwayr');
insert into customer (id, name, funds, type) values (647, 'Beltran Lorentz', 955, 'Agnibilékrou');
insert into customer (id, name, funds, type) values (648, 'Luise Robelow', 258, 'Kokkónion');
insert into customer (id, name, funds, type) values (649, 'Tracie Finlayson', 546, 'Cikeusal');
insert into customer (id, name, funds, type) values (650, 'Vanessa Ethersey', 215, 'Limbuš');
insert into customer (id, name, funds, type) values (651, 'Eveline Cowle', 740, 'San Antonio');
insert into customer (id, name, funds, type) values (652, 'Ephrayim Fingleton', 505, 'Cran-Gevrier');
insert into customer (id, name, funds, type) values (653, 'Gil MacCracken', 257, 'Tyczyn');
insert into customer (id, name, funds, type) values (654, 'Zorana Dansie', 937, 'Haputale');
insert into customer (id, name, funds, type) values (655, 'Jaquelin Goymer', 340, 'Maliang');
insert into customer (id, name, funds, type) values (656, 'Hastings Hospital', 513, 'Kunwi');
insert into customer (id, name, funds, type) values (657, 'Shell Sallery', 364, 'Toyokawa');
insert into customer (id, name, funds, type) values (658, 'Caspar Dwyr', 579, 'Old Harbour Bay');
insert into customer (id, name, funds, type) values (659, 'Morganne Bonds', 446, 'Parakanpanjang');
insert into customer (id, name, funds, type) values (660, 'Margalit Pointer', 246, 'Bongsri');
insert into customer (id, name, funds, type) values (661, 'Rosemary Linturn', 715, 'Pagaden');
insert into customer (id, name, funds, type) values (662, 'Sheila-kathryn Dalla', 362, 'Shimen');
insert into customer (id, name, funds, type) values (663, 'Curt O'' Liddy', 116, 'Mbanga');
insert into customer (id, name, funds, type) values (664, 'Quill Coules', 65, 'Damaturu');
insert into customer (id, name, funds, type) values (665, 'Billie Priscott', 964, 'Companhia de Baixo');
insert into customer (id, name, funds, type) values (666, 'Freddie Kerwood', 60, 'Khōshāmand');
insert into customer (id, name, funds, type) values (667, 'Otes Rikard', 504, 'Kuching');
insert into customer (id, name, funds, type) values (668, 'Myrilla Trebble', 450, 'Prokuplje');
insert into customer (id, name, funds, type) values (669, 'Florry Gamon', 365, 'Pojan');
insert into customer (id, name, funds, type) values (670, 'Joy Chastey', 387, 'Reshetikha');
insert into customer (id, name, funds, type) values (671, 'Gennie Schenkel', 204, 'Qijiawan');
insert into customer (id, name, funds, type) values (672, 'Wiley Ollerhad', 294, 'Datuan');
insert into customer (id, name, funds, type) values (673, 'Caz Batting', 393, 'Huashi');
insert into customer (id, name, funds, type) values (674, 'Zea Robiot', 287, 'Santa Rosa');
insert into customer (id, name, funds, type) values (675, 'Joelie Ambrogioli', 317, 'Cisarap');
insert into customer (id, name, funds, type) values (676, 'Leesa Pain', 922, 'Gajrug');
insert into customer (id, name, funds, type) values (677, 'Archie Napolitano', 605, 'Koropí');
insert into customer (id, name, funds, type) values (678, 'Lauralee Kenn', 218, 'Bezenchuk');
insert into customer (id, name, funds, type) values (679, 'Welsh Yekel', 441, '‘Anātā');
insert into customer (id, name, funds, type) values (680, 'Jessa Gatchel', 918, 'Sanhe');
insert into customer (id, name, funds, type) values (681, 'Iggie MacDunlevy', 71, 'Xagmakajor');
insert into customer (id, name, funds, type) values (682, 'Sydelle Roney', 403, 'Punaauia');
insert into customer (id, name, funds, type) values (683, 'Ania Rudall', 119, 'Bonpland');
insert into customer (id, name, funds, type) values (684, 'Dido McGeraghty', 145, 'Kafr al Labad');
insert into customer (id, name, funds, type) values (685, 'Rudiger Cousin', 487, 'Kirawsk');
insert into customer (id, name, funds, type) values (686, 'Fairlie Agastina', 861, 'Diré');
insert into customer (id, name, funds, type) values (687, 'Munroe Fasler', 121, 'Almaguer North');
insert into customer (id, name, funds, type) values (688, 'Rickert Lankham', 400, 'San Isidro');
insert into customer (id, name, funds, type) values (689, 'Bobinette Goodrich', 865, 'Pyatigorskiy');
insert into customer (id, name, funds, type) values (690, 'Darrelle Count', 553, 'Pachīr wa Āgām');
insert into customer (id, name, funds, type) values (691, 'Nickie Kave', 7, 'Cruzeiro');
insert into customer (id, name, funds, type) values (692, 'Aloysius Metson', 938, 'Haruman');
insert into customer (id, name, funds, type) values (693, 'Gwenneth Bish', 637, 'Oju');
insert into customer (id, name, funds, type) values (694, 'Morrie Rozier', 930, 'Vanino');
insert into customer (id, name, funds, type) values (695, 'Avis Guiot', 405, 'Velyki Kopany');
insert into customer (id, name, funds, type) values (696, 'Lonna McBeth', 88, 'Yangyong');
insert into customer (id, name, funds, type) values (697, 'Angy Kenrick', 494, 'Bello');
insert into customer (id, name, funds, type) values (698, 'Desmond McSwan', 799, 'Renfrew');
insert into customer (id, name, funds, type) values (699, 'Benedict Norquay', 417, 'Mel’nikovo');
insert into customer (id, name, funds, type) values (700, 'Tiena O''Kinedy', 477, 'Włoszczowa');
insert into customer (id, name, funds, type) values (701, 'Haley Chennells', 448, 'Dongkeng');
insert into customer (id, name, funds, type) values (702, 'Brocky Gerrit', 66, 'Fenshui');
insert into customer (id, name, funds, type) values (703, 'Hunfredo Finnan', 754, 'Corupá');
insert into customer (id, name, funds, type) values (704, 'Lonee Cabrara', 924, 'Wucun');
insert into customer (id, name, funds, type) values (705, 'Carson Dreinan', 578, 'Bojongsarung');
insert into customer (id, name, funds, type) values (706, 'Krissie Felderer', 796, 'Sarpang');
insert into customer (id, name, funds, type) values (707, 'Carr McNeice', 198, 'Fangcun');
insert into customer (id, name, funds, type) values (708, 'Bevon Crossan', 6, 'Semënov');
insert into customer (id, name, funds, type) values (709, 'Lona Dupoy', 42, 'Doksy');
insert into customer (id, name, funds, type) values (710, 'Sigrid Tuxsell', 370, 'Penápolis');
insert into customer (id, name, funds, type) values (711, 'Court Chamney', 955, 'Sindangraja');
insert into customer (id, name, funds, type) values (712, 'Addie Cozins', 238, 'Penitik');
insert into customer (id, name, funds, type) values (713, 'Ingeborg Walsom', 250, 'Pavliš');
insert into customer (id, name, funds, type) values (714, 'Darci Biffin', 621, 'Ibotirama');
insert into customer (id, name, funds, type) values (715, 'Emmalyn Christophe', 630, 'Anáfi');
insert into customer (id, name, funds, type) values (716, 'Candi Growy', 433, 'Sumy');
insert into customer (id, name, funds, type) values (717, 'Edithe McVeighty', 466, 'Pancoran');
insert into customer (id, name, funds, type) values (718, 'Giacobo Forrest', 19, 'Tylicz');
insert into customer (id, name, funds, type) values (719, 'Mile Rickerd', 580, 'Kalebun');
insert into customer (id, name, funds, type) values (720, 'Terrance Dever', 133, 'Rudong');
insert into customer (id, name, funds, type) values (721, 'Siobhan Harrill', 142, 'Klimontów');
insert into customer (id, name, funds, type) values (722, 'Porter Vowles', 58, 'Ngancar');
insert into customer (id, name, funds, type) values (723, 'Onfroi Andren', 624, 'Hodoš');
insert into customer (id, name, funds, type) values (724, 'Blakeley Tuffrey', 532, 'Otjimbingwe');
insert into customer (id, name, funds, type) values (725, 'Westbrook Butterfint', 474, 'Yangon');
insert into customer (id, name, funds, type) values (726, 'Helyn Vieyra', 514, 'Bastia');
insert into customer (id, name, funds, type) values (727, 'Vlad Pickford', 835, 'Rozhniv');
insert into customer (id, name, funds, type) values (728, 'Irv Matthews', 654, 'Phú Khương');
insert into customer (id, name, funds, type) values (729, 'Talbot Brahm', 882, 'Rancabungur');
insert into customer (id, name, funds, type) values (730, 'Mead Christophle', 122, 'Hebei');
insert into customer (id, name, funds, type) values (731, 'Cele Glasscoo', 592, 'De la Paz');
insert into customer (id, name, funds, type) values (732, 'Pepita Coleridge', 756, 'Mehrābpur');
insert into customer (id, name, funds, type) values (733, 'Christophorus Everest', 534, 'Lujing Zhen');
insert into customer (id, name, funds, type) values (734, 'Sara-ann Dilrew', 838, 'El Carril');
insert into customer (id, name, funds, type) values (735, 'Loretta Orteaux', 226, 'Uruguaiana');
insert into customer (id, name, funds, type) values (736, 'Kristy Izhakov', 472, 'Rezé');
insert into customer (id, name, funds, type) values (737, 'Dacy Degoix', 281, 'Vol’no-Nadezhdinskoye');
insert into customer (id, name, funds, type) values (738, 'Wes Merrgen', 230, 'Al Qamşīyah');
insert into customer (id, name, funds, type) values (739, 'Jessamine Brantzen', 317, 'Santa Brigida');
insert into customer (id, name, funds, type) values (740, 'Rustin Urlich', 482, 'Juuka');
insert into customer (id, name, funds, type) values (741, 'Gennie Turbitt', 380, 'Göteborg');
insert into customer (id, name, funds, type) values (742, 'Mace Edser', 256, 'La Paz');
insert into customer (id, name, funds, type) values (743, 'Brigit Vineall', 780, 'Moss');
insert into customer (id, name, funds, type) values (744, 'Sallyann Walicki', 504, 'Tall Ḩamīs');
insert into customer (id, name, funds, type) values (745, 'Pauly Brion', 475, 'Lysice');
insert into customer (id, name, funds, type) values (746, 'Estell McGeagh', 494, 'Muldersdriseloop');
insert into customer (id, name, funds, type) values (747, 'Gray Carlone', 662, 'Svilengrad');
insert into customer (id, name, funds, type) values (748, 'Ynes Spoors', 236, 'Shreveport');
insert into customer (id, name, funds, type) values (749, 'Halli Zapata', 201, 'Novi Pazar');
insert into customer (id, name, funds, type) values (750, 'Blair Kurten', 137, 'Dhalie');
insert into customer (id, name, funds, type) values (751, 'Mano Tissell', 133, 'Mörön');
insert into customer (id, name, funds, type) values (752, 'Andie Kinnerk', 858, 'Victoria');
insert into customer (id, name, funds, type) values (753, 'Bennett Themann', 414, 'Czarna Woda');
insert into customer (id, name, funds, type) values (754, 'Jamaal Tong', 106, 'Si’erbao');
insert into customer (id, name, funds, type) values (755, 'Saunderson Fuller', 503, 'Nong Chik');
insert into customer (id, name, funds, type) values (756, 'Hope Giottini', 856, 'No Kunda');
insert into customer (id, name, funds, type) values (757, 'Buck Ecles', 499, 'Tianchang');
insert into customer (id, name, funds, type) values (758, 'Lazaro Lesper', 101, 'San Bernardo');
insert into customer (id, name, funds, type) values (759, 'Maxi Cantopher', 327, 'Krebet');
insert into customer (id, name, funds, type) values (760, 'Gerek Neath', 356, 'Xujia');
insert into customer (id, name, funds, type) values (761, 'Marylee Freiberg', 46, 'Carapo');
insert into customer (id, name, funds, type) values (762, 'Tildy Levins', 397, 'Piltown');
insert into customer (id, name, funds, type) values (763, 'Courtnay Hucks', 365, 'Shujāābād');
insert into customer (id, name, funds, type) values (764, 'Adrianna Curry', 200, 'Cikalang');
insert into customer (id, name, funds, type) values (765, 'Thalia McGregor', 208, 'Tingloy');
insert into customer (id, name, funds, type) values (766, 'Ashely Rudd', 134, 'Weetobula');
insert into customer (id, name, funds, type) values (767, 'Forster Staning', 479, 'Futtsu');
insert into customer (id, name, funds, type) values (768, 'Toby Gong', 771, 'Gikongoro');
insert into customer (id, name, funds, type) values (769, 'Fidole Harrema', 824, 'Salaverry');
insert into customer (id, name, funds, type) values (770, 'Link Dreger', 788, 'Talakag');
insert into customer (id, name, funds, type) values (771, 'Consolata Lippitt', 862, 'Mekarsari');
insert into customer (id, name, funds, type) values (772, 'Prinz Siely', 175, 'Liudu');
insert into customer (id, name, funds, type) values (773, 'Damita Bassilashvili', 88, 'Panggungsari');
insert into customer (id, name, funds, type) values (774, 'Konrad Colbron', 234, 'Marathókampos');
insert into customer (id, name, funds, type) values (775, 'Rivalee Artingstall', 557, 'Tekeli');
insert into customer (id, name, funds, type) values (776, 'Daniela Lubomirski', 798, 'Agnibilékrou');
insert into customer (id, name, funds, type) values (777, 'Myrtie Linsley', 563, 'Dallas');
insert into customer (id, name, funds, type) values (778, 'Asa Osborn', 451, 'Hongqiao');
insert into customer (id, name, funds, type) values (779, 'Curran Cochran', 957, 'Shancheng');
insert into customer (id, name, funds, type) values (780, 'Cosmo Forten', 478, 'Lyon');
insert into customer (id, name, funds, type) values (781, 'Eugenie Mattisson', 813, 'Sumberjo');
insert into customer (id, name, funds, type) values (782, 'Vanya Burk', 483, 'Taraz');
insert into customer (id, name, funds, type) values (783, 'Cleon Stanfield', 942, 'Pangushan');
insert into customer (id, name, funds, type) values (784, 'Darryl Ladell', 995, 'Čížkovice');
insert into customer (id, name, funds, type) values (785, 'Roxy Titchener', 139, 'Chegutu');
insert into customer (id, name, funds, type) values (786, 'Cinderella Bromilow', 739, 'Opi');
insert into customer (id, name, funds, type) values (787, 'Leilah Edgcombe', 206, 'Isehara');
insert into customer (id, name, funds, type) values (788, 'Serena Birmingham', 521, 'Moryń');
insert into customer (id, name, funds, type) values (789, 'Orv McKerton', 875, 'Qinhong');
insert into customer (id, name, funds, type) values (790, 'Alexei Higgoe', 176, 'Zhangjiafan');
insert into customer (id, name, funds, type) values (791, 'Nara Granville', 348, 'Rizal');
insert into customer (id, name, funds, type) values (792, 'Hugh Placstone', 607, 'Chojata');
insert into customer (id, name, funds, type) values (793, 'Jyoti Grain', 862, 'Jāti');
insert into customer (id, name, funds, type) values (794, 'Adelice Takis', 399, 'Wuxia');
insert into customer (id, name, funds, type) values (795, 'Annemarie Barthelme', 951, 'Novomoskovs’k');
insert into customer (id, name, funds, type) values (796, 'Lorie Peasegod', 219, 'Navegantes');
insert into customer (id, name, funds, type) values (797, 'Issi Bitcheno', 810, 'Hovorany');
insert into customer (id, name, funds, type) values (798, 'Muffin Tie', 333, 'Mjölby');
insert into customer (id, name, funds, type) values (799, 'Eilis Thunnercliffe', 213, 'Korosten’');
insert into customer (id, name, funds, type) values (800, 'Sharla Linfitt', 107, 'Lanos');
insert into customer (id, name, funds, type) values (801, 'Arliene Simpkin', 977, 'Boulder');
insert into customer (id, name, funds, type) values (802, 'Emelda Seid', 515, 'Akat Amnuai');
insert into customer (id, name, funds, type) values (803, 'Flory Hamments', 390, 'Bandeirantes');
insert into customer (id, name, funds, type) values (804, 'Tony Lawlan', 213, 'Fairview');
insert into customer (id, name, funds, type) values (805, 'Annabal Lorden', 155, 'Levashi');
insert into customer (id, name, funds, type) values (806, 'Jacinda Rutgers', 54, 'Kambingan');
insert into customer (id, name, funds, type) values (807, 'Todd Ruddom', 800, 'Anchorage');
insert into customer (id, name, funds, type) values (808, 'Sibby Ladell', 202, 'Kampene');
insert into customer (id, name, funds, type) values (809, 'Ginnifer Oboy', 772, 'Kermānshāh');
insert into customer (id, name, funds, type) values (810, 'Kassandra Gauche', 111, 'Wuma');
insert into customer (id, name, funds, type) values (811, 'Marjie Shay', 684, 'Nueva Arica');
insert into customer (id, name, funds, type) values (812, 'Avery Filippo', 288, 'Russeifa');
insert into customer (id, name, funds, type) values (813, 'Isabelita Pott', 222, 'Cimonyong');
insert into customer (id, name, funds, type) values (814, 'Cyrille Spira', 434, 'Vandœuvre-lès-Nancy');
insert into customer (id, name, funds, type) values (815, 'Rand Ropartz', 895, 'Halat');
insert into customer (id, name, funds, type) values (816, 'Colan Pearson', 967, 'Somerset East');
insert into customer (id, name, funds, type) values (817, 'Dyanna Wedlake', 847, 'Toyonaka');
insert into customer (id, name, funds, type) values (818, 'Rosaline Daggett', 107, 'Jiangyan');
insert into customer (id, name, funds, type) values (819, 'Bethanne Ballintyne', 155, 'Taounza');
insert into customer (id, name, funds, type) values (820, 'Tiffy Samples', 347, 'Guabito');
insert into customer (id, name, funds, type) values (821, 'Corenda Willacot', 56, 'Arlington');
insert into customer (id, name, funds, type) values (822, 'Sofie Tomney', 837, 'Caieiras');
insert into customer (id, name, funds, type) values (823, 'Aprilette Minster', 924, 'Shangzhuang');
insert into customer (id, name, funds, type) values (824, 'Rosanna Woodford', 454, 'Ordynskoye');
insert into customer (id, name, funds, type) values (825, 'Annabell Marchand', 412, 'Chateaubelair');
insert into customer (id, name, funds, type) values (826, 'Jon Pitts', 256, 'Skärholmen');
insert into customer (id, name, funds, type) values (827, 'Cindie Biasioli', 342, 'Vysokogornyy');
insert into customer (id, name, funds, type) values (828, 'Barnabas Seymer', 557, 'El Bálsamo');
insert into customer (id, name, funds, type) values (829, 'Gray Clover', 859, 'Quinarayan');
insert into customer (id, name, funds, type) values (830, 'Lotta Reddle', 923, 'Mshinskaya');
insert into customer (id, name, funds, type) values (831, 'Sonja Laydel', 826, 'Anjani Barat');
insert into customer (id, name, funds, type) values (832, 'Heywood Rosenstein', 78, 'Ystad');
insert into customer (id, name, funds, type) values (833, 'Mirabelle Snell', 454, 'Dniprodzerzhyns’k');
insert into customer (id, name, funds, type) values (834, 'Decca Jeffcoat', 47, 'Kuvshinovo');
insert into customer (id, name, funds, type) values (835, 'Laraine Marjoram', 12, 'Kerva');
insert into customer (id, name, funds, type) values (836, 'Dorella Jaukovic', 298, 'Chongqing');
insert into customer (id, name, funds, type) values (837, 'Sherwood Gabbitus', 681, 'Muricay');
insert into customer (id, name, funds, type) values (838, 'Booth Goldsbrough', 296, 'Mae Ramat');
insert into customer (id, name, funds, type) values (839, 'Ossie Caulliere', 307, 'Tongjin');
insert into customer (id, name, funds, type) values (840, 'Rachelle Tyndall', 6, 'Penza');
insert into customer (id, name, funds, type) values (841, 'Eunice Hasell', 925, 'Pingwang');
insert into customer (id, name, funds, type) values (842, 'Talbot Balf', 896, 'Guanzhuang');
insert into customer (id, name, funds, type) values (843, 'Janith Cecere', 145, 'Yaruchel');
insert into customer (id, name, funds, type) values (844, 'Birk Manoch', 565, 'Wodzisław Śląski');
insert into customer (id, name, funds, type) values (845, 'Iggie Upshall', 820, 'Embarcación');
insert into customer (id, name, funds, type) values (846, 'Shelby Benedek', 395, 'El Jem');
insert into customer (id, name, funds, type) values (847, 'Gene Farrington', 16, 'Ol’ginka');
insert into customer (id, name, funds, type) values (848, 'Heywood Strowther', 726, 'Montigny-lès-Metz');
insert into customer (id, name, funds, type) values (849, 'Hewie Bowich', 181, 'Chernyanka');
insert into customer (id, name, funds, type) values (850, 'Emmye Pottiphar', 230, 'Labège');
insert into customer (id, name, funds, type) values (851, 'Garnet Torres', 601, 'Bailu');
insert into customer (id, name, funds, type) values (852, 'Brigit Hows', 588, 'Concórdia');
insert into customer (id, name, funds, type) values (853, 'Wandis Townby', 54, 'Petare');
insert into customer (id, name, funds, type) values (854, 'Belinda McCuis', 493, 'Heshui');
insert into customer (id, name, funds, type) values (855, 'Job Kedwell', 995, 'Pojan');
insert into customer (id, name, funds, type) values (856, 'Danika Kleen', 481, 'Vrbice');
insert into customer (id, name, funds, type) values (857, 'Natal Alastair', 254, 'Kangping');
insert into customer (id, name, funds, type) values (858, 'Siana Lomis', 192, 'Santa');
insert into customer (id, name, funds, type) values (859, 'Willard Holby', 954, 'La Tinguiña');
insert into customer (id, name, funds, type) values (860, 'Tristam Wyeth', 504, 'Araci');
insert into customer (id, name, funds, type) values (861, 'Obadias Alves', 975, 'Tonghu');
insert into customer (id, name, funds, type) values (862, 'Thaine Tollerton', 597, 'Guachucal');
insert into customer (id, name, funds, type) values (863, 'Zared Brisse', 900, 'Xinxing');
insert into customer (id, name, funds, type) values (864, 'Veronica MacArthur', 36, 'Pedome');
insert into customer (id, name, funds, type) values (865, 'Dominica Sommerfeld', 909, 'Oro Timur');
insert into customer (id, name, funds, type) values (866, 'Camella Ferryman', 310, 'Yuli');
insert into customer (id, name, funds, type) values (867, 'Constance Tuminelli', 488, 'Sarulla');
insert into customer (id, name, funds, type) values (868, 'Marisa Pundy', 693, 'Maumere');
insert into customer (id, name, funds, type) values (869, 'Conny Bleasdille', 891, 'Kirovohrad');
insert into customer (id, name, funds, type) values (870, 'Sloane Lacelett', 150, 'Chalandrítsa');
insert into customer (id, name, funds, type) values (871, 'Jorge Garforth', 580, 'Terezín');
insert into customer (id, name, funds, type) values (872, 'Gussie Ormond', 113, 'Huocheng');
insert into customer (id, name, funds, type) values (873, 'Geri Duetsche', 40, 'Date');
insert into customer (id, name, funds, type) values (874, 'Olia MacGorman', 708, 'Boguchar');
insert into customer (id, name, funds, type) values (875, 'Jon Baunton', 997, 'Parabcan');
insert into customer (id, name, funds, type) values (876, 'Darrin Pues', 331, 'Aix-en-Provence');
insert into customer (id, name, funds, type) values (877, 'Alley Tschierasche', 355, 'Chengtian');
insert into customer (id, name, funds, type) values (878, 'Athena Dadds', 336, 'Chafé');
insert into customer (id, name, funds, type) values (879, 'Deerdre Hawkswood', 61, 'Ulundi');
insert into customer (id, name, funds, type) values (880, 'Saunder Brierley', 915, 'Fak Tha');
insert into customer (id, name, funds, type) values (881, 'Goddard Rydeard', 472, 'Aya');
insert into customer (id, name, funds, type) values (882, 'Toni Beretta', 716, 'Magdalena');
insert into customer (id, name, funds, type) values (883, 'Josy Ison', 165, 'Angers');
insert into customer (id, name, funds, type) values (884, 'Keri Dils', 716, 'Beihe');
insert into customer (id, name, funds, type) values (885, 'Cate Rouge', 2, 'Yuanqian');
insert into customer (id, name, funds, type) values (886, 'Emmit Parish', 21, 'Tam Bình');
insert into customer (id, name, funds, type) values (887, 'Joelle Raycroft', 708, 'Salinas');
insert into customer (id, name, funds, type) values (888, 'Elnore Stagge', 751, 'Xinhe');
insert into customer (id, name, funds, type) values (889, 'Sande Acom', 662, 'Mawa');
insert into customer (id, name, funds, type) values (890, 'Kylie Cardiff', 635, 'Al Hufūf');
insert into customer (id, name, funds, type) values (891, 'Konstantine Preskett', 450, 'Chengyang');
insert into customer (id, name, funds, type) values (892, 'Vanya Waddilow', 850, 'Söderhamn');
insert into customer (id, name, funds, type) values (893, 'Lena Braunds', 239, 'Lapuan');
insert into customer (id, name, funds, type) values (894, 'Georges Braithwaite', 60, 'Zhaodong');
insert into customer (id, name, funds, type) values (895, 'Golda Savery', 355, 'Junín');
insert into customer (id, name, funds, type) values (896, 'Russell Apted', 947, 'Olesno');
insert into customer (id, name, funds, type) values (897, 'Winny MacBean', 324, 'Warmbaths');
insert into customer (id, name, funds, type) values (898, 'Ami Champneys', 162, 'Tamuning-Tumon-Harmon Village');
insert into customer (id, name, funds, type) values (899, 'Joli Carneck', 490, 'Santana do Ipanema');
insert into customer (id, name, funds, type) values (900, 'Tate Mitchall', 884, 'Xinbei');
insert into customer (id, name, funds, type) values (901, 'Fancie Stuck', 168, 'Bavorov');
insert into customer (id, name, funds, type) values (902, 'Jenni Rorke', 494, 'Dijon');
insert into customer (id, name, funds, type) values (903, 'Theobald Juorio', 967, 'Shengtang');
insert into customer (id, name, funds, type) values (904, 'Chad Zemler', 961, 'Nyakhachava');
insert into customer (id, name, funds, type) values (905, 'Avictor Checcucci', 293, 'Pilar do Sul');
insert into customer (id, name, funds, type) values (906, 'Chariot Tumpane', 166, 'Shanxi');
insert into customer (id, name, funds, type) values (907, 'Nat Chatenier', 549, 'Boguszów-Gorce');
insert into customer (id, name, funds, type) values (908, 'Aubrie Keymer', 320, 'Mambalan');
insert into customer (id, name, funds, type) values (909, 'Othilie Jedrasik', 720, 'Wuning');
insert into customer (id, name, funds, type) values (910, 'Rose Meale', 347, 'Daszewice');
insert into customer (id, name, funds, type) values (911, 'Jessie Slemming', 503, 'Krasnoye');
insert into customer (id, name, funds, type) values (912, 'Brewer Hof', 872, 'Caldono');
insert into customer (id, name, funds, type) values (913, 'Lishe Skeermor', 212, 'Saint-Pierre-des-Corps');
insert into customer (id, name, funds, type) values (914, 'Cortney Grinvalds', 282, 'Klisura');
insert into customer (id, name, funds, type) values (915, 'Alfred Coleford', 802, 'Abomey-Calavi');
insert into customer (id, name, funds, type) values (916, 'Janeen Olphert', 765, 'Poyang');
insert into customer (id, name, funds, type) values (917, 'Gris Gansbuhler', 876, 'Rumboci');
insert into customer (id, name, funds, type) values (918, 'Gaspard Dallison', 212, 'Zongga');
insert into customer (id, name, funds, type) values (919, 'Malvina Kinig', 771, 'Independencia');
insert into customer (id, name, funds, type) values (920, 'Benton Goodsir', 640, 'Jessore');
insert into customer (id, name, funds, type) values (921, 'Aleta Tapton', 685, 'Vievis');
insert into customer (id, name, funds, type) values (922, 'Cobbie Jaeggi', 988, 'Chumphon');
insert into customer (id, name, funds, type) values (923, 'Gran Eastway', 897, 'Waihibar');
insert into customer (id, name, funds, type) values (924, 'Candie Lathe', 240, 'Jinping');
insert into customer (id, name, funds, type) values (925, 'Hinda Sparshatt', 113, 'Piancheng');
insert into customer (id, name, funds, type) values (926, 'Stafani Izachik', 194, 'Delft');
insert into customer (id, name, funds, type) values (927, 'Sharia Goldthorpe', 239, 'Świeradów-Zdrój');
insert into customer (id, name, funds, type) values (928, 'Jaimie Kinney', 354, 'Jianfeng');
insert into customer (id, name, funds, type) values (929, 'Kimbell Andrichak', 697, 'Yangqiaodian');
insert into customer (id, name, funds, type) values (930, 'Chiquita Pounsett', 361, 'Sydney');
insert into customer (id, name, funds, type) values (931, 'Cherice Gorry', 352, 'Pukou');
insert into customer (id, name, funds, type) values (932, 'Elna Braybrookes', 912, 'Ribeirão Preto');
insert into customer (id, name, funds, type) values (933, 'Rickert Herrieven', 952, 'Proletarskiy');
insert into customer (id, name, funds, type) values (934, 'Cart Velareal', 870, 'Nanae');
insert into customer (id, name, funds, type) values (935, 'Aleda Snazle', 646, 'Boca Raton');
insert into customer (id, name, funds, type) values (936, 'Lorinda Grassin', 798, 'Huo’erqi');
insert into customer (id, name, funds, type) values (937, 'Lonnard MacKettrick', 64, 'Düsseldorf');
insert into customer (id, name, funds, type) values (938, 'Antonietta Knevet', 68, 'Hovd');
insert into customer (id, name, funds, type) values (939, 'Abbie Paulon', 565, 'Muktāgācha');
insert into customer (id, name, funds, type) values (940, 'Cliff Rowley', 214, 'Hongshan');
insert into customer (id, name, funds, type) values (941, 'Jereme Vondrasek', 736, 'Wuyo');
insert into customer (id, name, funds, type) values (942, 'Rick Snead', 573, 'Češinovo');
insert into customer (id, name, funds, type) values (943, 'Linell Matusov', 574, 'Porto Velho');
insert into customer (id, name, funds, type) values (944, 'Phillipp Turle', 774, 'Huta Stara B');
insert into customer (id, name, funds, type) values (945, 'Gerrard Kumar', 377, 'Shazhouba');
insert into customer (id, name, funds, type) values (946, 'Galen Plenderleith', 818, 'Banjarkemuning');
insert into customer (id, name, funds, type) values (947, 'Sibby Gerrell', 140, 'Saint-Étienne');
insert into customer (id, name, funds, type) values (948, 'Fraser Farrears', 84, 'Asquipata');
insert into customer (id, name, funds, type) values (949, 'Manya Perham', 424, 'Peicheng');
insert into customer (id, name, funds, type) values (950, 'Innis Doles', 309, 'Karlskoga');
insert into customer (id, name, funds, type) values (951, 'Eddie Deller', 582, 'Falkenberg');
insert into customer (id, name, funds, type) values (952, 'Rab Earwicker', 178, 'Tinabogan');
insert into customer (id, name, funds, type) values (953, 'Franciska Dearan', 850, 'Lesnoy');
insert into customer (id, name, funds, type) values (954, 'Jeromy Schuler', 954, 'Šentilj v Slov. Goricah');
insert into customer (id, name, funds, type) values (955, 'Lurline Baudou', 911, 'Changfeng');
insert into customer (id, name, funds, type) values (956, 'Clevey Barthram', 862, 'Krajan Dua Padomasan');
insert into customer (id, name, funds, type) values (957, 'Gery Matches', 357, 'Cherëmukhovo');
insert into customer (id, name, funds, type) values (958, 'Saree Curle', 627, 'Zibo');
insert into customer (id, name, funds, type) values (959, 'Conni Redon', 985, 'Bhakkar');
insert into customer (id, name, funds, type) values (960, 'Alistair Prosh', 497, 'Rasskazovo');
insert into customer (id, name, funds, type) values (961, 'Lane Beiderbecke', 297, 'Yabluniv');
insert into customer (id, name, funds, type) values (962, 'Patin Joiner', 843, 'Mae Wang');
insert into customer (id, name, funds, type) values (963, 'Muffin Cockerill', 547, 'Kagay');
insert into customer (id, name, funds, type) values (964, 'Hattie Silveston', 908, 'Breda');
insert into customer (id, name, funds, type) values (965, 'Wendye Backs', 439, 'Sonta');
insert into customer (id, name, funds, type) values (966, 'Melicent L''argent', 93, 'Ḩalḩūl');
insert into customer (id, name, funds, type) values (967, 'Frants McTurlough', 642, 'Zhongzhang');
insert into customer (id, name, funds, type) values (968, 'Lynnell Jirka', 113, 'Hezhi');
insert into customer (id, name, funds, type) values (969, 'Lilyan Drennan', 378, 'Louny');
insert into customer (id, name, funds, type) values (970, 'Jo Wolverson', 29, 'Curitibanos');
insert into customer (id, name, funds, type) values (971, 'Dorine Dumini', 395, 'Kaminokawa');
insert into customer (id, name, funds, type) values (972, 'Ulysses Long', 575, 'Libei');
insert into customer (id, name, funds, type) values (973, 'Daniela Cellone', 438, 'Xingtan');
insert into customer (id, name, funds, type) values (974, 'Travis Mitford', 495, 'Nikita');
insert into customer (id, name, funds, type) values (975, 'Tonie Crampsy', 534, 'Hinapalanan');
insert into customer (id, name, funds, type) values (976, 'Montgomery Louder', 852, 'Rufino');
insert into customer (id, name, funds, type) values (977, 'Fanechka Sturney', 211, 'Tuojiang');
insert into customer (id, name, funds, type) values (978, 'Lalo Szymanski', 60, 'Xieshui');
insert into customer (id, name, funds, type) values (979, 'Grete Battill', 713, 'Qal‘at Bīshah');
insert into customer (id, name, funds, type) values (980, 'Alain Di Biasi', 304, 'Xinyu');
insert into customer (id, name, funds, type) values (981, 'Harri Whitaker', 481, 'Utan');
insert into customer (id, name, funds, type) values (982, 'Kissie Linsley', 882, 'Peristerá');
insert into customer (id, name, funds, type) values (983, 'Saree Balme', 473, 'Mae Lan');
insert into customer (id, name, funds, type) values (984, 'Junie Caesar', 822, 'Yermolino');
insert into customer (id, name, funds, type) values (985, 'Rollo Crocetto', 709, 'Hulei');
insert into customer (id, name, funds, type) values (986, 'Jana Lehemann', 465, 'Urek-urek');
insert into customer (id, name, funds, type) values (987, 'Pepi Sainthill', 222, 'Tunasbaru');
insert into customer (id, name, funds, type) values (988, 'Cathrine Tayt', 423, 'Lenešice');
insert into customer (id, name, funds, type) values (989, 'Elyse McElwee', 715, 'Fernández');
insert into customer (id, name, funds, type) values (990, 'Lucienne Clewer', 588, 'Venda');
insert into customer (id, name, funds, type) values (991, 'Alister Tuxsell', 928, 'Chenxikou');
insert into customer (id, name, funds, type) values (992, 'Karlotte Silvester', 77, 'Shangtang');
insert into customer (id, name, funds, type) values (993, 'Liane Shelborne', 147, 'Glamang');
insert into customer (id, name, funds, type) values (994, 'Tine Churches', 601, 'Pondohan');
insert into customer (id, name, funds, type) values (995, 'Meryl Fordham', 695, 'Stockholm');
insert into customer (id, name, funds, type) values (996, 'Amanda O''Donegan', 629, 'Idhnā');
insert into customer (id, name, funds, type) values (997, 'Egan Stowte', 585, 'Lorengau');
insert into customer (id, name, funds, type) values (998, 'Anne-corinne McGuggy', 98, 'Yujing');
insert into customer (id, name, funds, type) values (999, 'Anni McLarty', 885, 'Jixing');
insert into customer (id, name, funds, type) values (1000, 'Quincy Huxton', 569, 'Sevsk');