spring:
  application:
    name: product-service
  datasource:
    url: ${vcap.services.cleardb.credentials.jdbcUrl:jdbc:mysql://127.0.0.1:33306/chaos?useSSL=false}
    username: ${vcap.services.cleardb.credentials.username:chaos}
    password: ${vcap.services.cleardb.credentials.password:chaos123}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
chaos:
  monkey:
    enabled: true
    assaults:
      level: 7
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: true
    watcher:
      repository: true
      restController: true
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"