spring:
  application:
    name: product-service
  jpa:
    generate-ddl: false
  datasource:
    initialize: false

chaos:
  monkey:
    enabled: true
    assaults:
      level: 7
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: true
    watcher:
      repository: true
      restController: true

endpoints:
  chaosmonkey:
    enabled: true
      
management:
  security:
    enabled: false

